### ISSUE TITLE
[BUG] Random iOS Crash GRBackendRenderTarget.GetGlFramebufferInfo()

### ISSUE THREAD

**Issue by RRTroodter** [mono/SkiaSharp#910] opened 2019-07-09 17:52 UTC
**Description**

Seeing random gr_backendrendertarget_get_gl_framebufferinfo crashes in AppCenter for the iOS versions of our app. Not seeing this problem for Android.

**Code**

Calls into this method are coming in from FFImageLoading (Xamarin.FFImageLoading.Svg.Forms (2.4.11.982)), which we use to render simple SVG images. Here is an example stack trace from AppCenter:
(SIGSEGV Crash)
gr_backendrendertarget_get_gl_framebufferinfo
gr_backendrendertarget_get_gl_framebufferinfo
gr_backendrendertarget_get_gl_framebufferinfo
gr_backendrendertarget_get_gl_framebufferinfo
sk_picture_recorder_delete
wrapper_managed_to_native_SkiaSharp_SkiaApi_sk_picture_recorder_delete_intptr <unknown>:1
SkiaSharp_SKPictureRecorder_Dispose_bool <unknown>:1
SkiaSharp_SKNativeObject_Dispose <unknown>:1
FFImageLoading_Svg_Platform_SKSvg_Load_System_Xml_Linq_XDocument (C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SkSvg.cs:208)
FFImageLoading_Svg_Platform_SKSvg_Load_System_Xml_XmlReader (C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SkSvg.cs:98)
FFImageLoading_Svg_Platform_SKSvg_Load_System_IO_Stream (C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SkSvg.cs:92)
FFImageLoading_Svg_Platform_SvgDataResolver__Resolved__22_MoveNext (C:\projects\ffimageloading\source\FFImageLoading.Svg.Shared\SvgDataResolver.cs:232)
AsyncMethodBuilder.cs:471
FFImageLoading_Svg_Platform_SvgDataResolver_Resolve_string_FFImageLoading_Work_TaskParameter_System_Threading_CancellationToken
FFImageLoading_DataResolvers_WrappedDataResolver__Resolved__2_MoveNext (C:\projects\ffimageloading\source\FFImageLoading.Common\DataResolvers\WrappedDataResolver.cs:21)
AsyncMethodBuilder.cs:471
FFImageLoading_DataResolvers_WrappedDataResolver_Resolve_string_FFImageLoading_Work_TaskParameter_System_Threading_CancellationToken
FFImageLoading_Work_ImageLoaderTask_3__RunAsyncd__109_TDecoderContainer_REF_TImageContainer_REF_TImageView_REF_MoveNext (C:\projects\ffimageloading\source\FFImageLoading.Common\Work\ImageLoaderTask.cs:603)
System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object
System_Threading_ExecutionContext_RunInternal_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool
System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_Run
System_Threading_Tasks_AwaitTaskContinuation_RunOrScheduleAction_System_Action_bool_System_Threading_Tasks_Task_
System_Threading_Tasks_Task_FinishContinuations
System_Threading_Tasks_Task_FinishStageThree
System_Threading_Tasks_Task_1_System_Threading_Tasks_VoidTaskResult_TrySetResult_System_Threading_Tasks_VoidTaskResult
System_Threading_Tasks_Task_DelayPromise_Complete
System_Threading_Tasks_Task__c__Delayb__249_1_object
System_Threading_Timer_Scheduler_TimerCB_object
System_Threading_QueueUserWorkItemCallback_System_Threading_IThreadPoolWorkItem_ExecuteWorkItem
System_Threading_ThreadPoolWorkQueue_Dispatch
Runtime.cs:280
System_Threading__ThreadPoolWaitCallback_PerformWaitCallback
wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr
mono_jit_runtime_invoke mini-runtime.c:3050
mono_runtime_try_invoke object.c:2942
worker_callback threadpool.c:282
worker_thread threadpool-worker-default.c:493
start_wrapper_internal threads.c:1098
start_wrapper threads.c:1158
libsystem_pthread.dylib
_pthread_body

**Expected Behavior**

No crashes

**Actual Behavior**

Random crashes

**Basic Information**

- Version with issue:  1.68.0
- Last known good version:  (none)
- IDE:  Visual Studio 2019
- Platform Target Frameworks:
  - iOS:  11.3.1, 11.4.1, 12.0, 12.1.4, 12.2, 12.3.1
- Target Devices:   iphones: 6, 6Plus, 6s, 6s Plus, SE, 7, 7 Plus, 8, 8 Plus, X, XR, XS Max

**Screenshots**

**Reproduction Link**

**Comment by mikepotvin** [comment] 2019-08-02 15:47
I've also been receiving similar reports. Still looking into a root cause or if there's any patterns but haven't found anything yet.

**Comment by stfnilsson** [comment] 2019-08-19 11:05
Any news about this?

**Comment by mattleibow** [comment] 2020-03-16 00:58
This might be a duplicate of #1121

**Comment by mattleibow** [comment] 2020-03-20 09:19
I have just published the PR (https://github.com/mono/SkiaSharp/pull/1180) NuGet (**1.68.2-pr.1180.1**) to the preview feed: https://aka.ms/skiasharp-eap/index.json
This contains the fixes for macOS, iOS and Android. More platforms coming soon.

Give that a go and let me know if it fixes the crashes.

**Closed** 2020-03-24 16:09 UTC

**Comment by mattleibow** [comment] 2020-03-24 21:04
Just pushed all the packages (preview 45) to NuGet.org.

**Comment by mattleibow** [comment] 2020-04-03 13:30
Hey folks, it has been a long time coming and thanks to all the folks with your repros, samples and stack traces I think we have finally managed to fix those pesky crashes - at least the ones we know about. I have just pushed **1.68.2-preview.50** to NuGet so let me know if this fixes all the crashes you have ever had 😄
