### ISSUE TITLE
[Bug] Whether SKTypeface and SKPaint instances are thread safe ?

### ISSUE THREAD

**Issue by VijayRM** [mono/SkiaSharp#1174] opened 2020-03-12 10:58 UTC
I have faced threading issue when I working with SKPaint & SKTypeface within our application but unable to replicate the same in simple project.

Whether SKTypeface and SKPaint instances are thread safe? Can we use it multi threading ? Disposing object in one thread affects in another thread?

Edited:

After some changes, i can reproduce the same issue in simple project. Please find the code from below
````
class Program
    {
        static void Main(string[] args)
        {
            
            for (int i = 0; i < 50; i++)
            {
                Console.WriteLine(i);
                Thread thread = new Thread(SkiaTypefaceThreading);
                thread.Name = i.ToString();
                thread.Start();
                
            }

        }
        private static void SkiaTypefaceThreading()
        {
            string[] fonts = new string[] { "Arial", "Verdana", "Calibri" };
            foreach (string fontName in fonts)
            {
                FontExtension ext = new FontExtension("Arial", 12);
                Console.WriteLine(ext.Typeface.FamilyName);
            }
            FontExtension.ClearFontCache();
        }
    }

public class FontExtension : SKPaint
    {
        [ThreadStatic]
        private static Dictionary<string, SKTypeface> typeFaceCache;
        public static Dictionary<string, SKTypeface> TypeFaceCache
        {
            get
            {
                if (typeFaceCache == null)
                    typeFaceCache = new Dictionary<string, SKTypeface>();
                return typeFaceCache;
            }
        }
        internal FontExtension(string fontName, float fontSize)
        {
            this.TextEncoding = SKTextEncoding.Utf8;
            this.IsAntialias = true;
            this.SubpixelText = true;
            
            if (TypeFaceCache != null && TypeFaceCache.ContainsKey(fontName + ";"))
                this.Typeface = TypeFaceCache[fontName + ";"];
            else
            {
                this.Typeface = SKTypeface.FromFamilyName(fontName, SKFontStyleWeight.Normal, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright); ;
                
                TypeFaceCache.Add(fontName + ";" , this.Typeface);
            }
            this.TextSize = fontSize;
        }
        public static void ClearFontCache()
        {
            
            if(typeFaceCache != null)
            {
                foreach (string key in typeFaceCache.Keys)
                {
                    SKTypeface sKTypeface = typeFaceCache[key];
                    if (sKTypeface != null)
                    {
                        sKTypeface.Dispose();
                        sKTypeface = null;
                    }
                }

                typeFaceCache.Clear();
                typeFaceCache = null;
            }
        }
    }
```
Please check this and provide suggestions to resolve the problem. Thanks in advance.

**Comment by ManishSync** [comment] 2020-04-15 06:20
Hi,

Any update on this?

Regards,
Manish R

**Comment by mattleibow** [comment] 2020-04-15 11:19
Duplicate of #1179

**Closed** 2020-04-15 11:20 UTC
Labels: type-duplicate

**Comment by mattleibow** [comment] 2020-04-15 11:23
@ManishSync check out the short thread on #1179
