### ISSUE TITLE
Right-To-Left text support

### ISSUE THREAD

**Issue by vrassouli** [mono/SkiaSharp#272] opened 2017-03-30 14:42 UTC
I'm trying to draw some Right-To-Left unicode text (Like Arabic or Persian) using DrawText method, but there is a problem with text rendering.
After finding the font, using the FontManager, I could draw the text, but it's in Left-To-Right order (like english) and the characters are separated, while right to left languages contains sticking-characters.
Is there any fix or workaround for this issue?

**Comment by mattleibow** [comment] 2017-03-30 19:21
I am not sure of the level of support for RTL.
Here is an old post with a bit of info: https://groups.google.com/forum/#!topic/skia-discuss/vSlrc-SPtkc

I would suggest asking on the skia forums as they can provide more detailed information: https://groups.google.com/forum/#!forum/skia-discuss

**Comment by vrassouli** [comment] 2017-03-31 09:52
I have implemented a very simple Custom View and it's render for android, and the drawing of text, renders correctly.
`    public class MyViewRenderer : ViewRenderer
    {
        public MyViewRenderer()
        {
            SetWillNotDraw(false);
        }

        public override void Draw(Canvas canvas)
        {
            var paint = new Paint
            {
                StrokeWidth = 10,
                Color = Color.Red,
                TextSize = 40
            };

            var text = "این یک متن فارسی است";
            canvas.DrawLine(0, 0, 100, 100, paint);
            canvas.DrawText(text, 200, 100, paint);
            base.Draw(canvas);
        }
    }
`
So, if the issue is from the Skia library itself, this implementation shouldn't work.
I believe, there is something wrong with SkiaSharp, since native implementations work fine.
By the way, this code, does not require to set the font. It seems, the default font of the system, already supports RTL languages (in this case, Farsi)

**Comment by tdenniston** [comment] 2017-03-31 14:28
@vrassouli @mattleibow I was also interested in this, so I looked in a bit. It appears the problem is in Skia, not SkiaSharp. See this fiddle for example: https://fiddle.skia.org/c/233fe257d13c6f87d39f6cd13e1054c7

I don't speak Farsi, but it looks like it is being rendered left-to-right. That indicates this is an issue in Skia, not SkiaSharp.

**Comment by mattleibow** [comment] 2017-03-31 17:31
I created a forum post just so that we can get some feedback on the "correct" way to draw text:
https://groups.google.com/forum/#!topic/skia-discuss/sMvI2oOdpNM

**Comment by migueldeicaza** [comment] 2017-04-04 19:19
From the responses it looks like we will have to surface SkShaper and SkTextBlobBuilder to C#

**Comment by roceh** [comment] 2017-04-24 09:05
+1 for harfbuzz support if its not to much KB (I suspect it might add a lot though..). I had a related issue with the current text renderer with font fallback (e.g. mixing European and Chinese glyphs for example in the same string on iOS). I managed to work around it using MatchCharacter but it wasn't fast or elegant.

**Comment by mattleibow** [comment] 2017-04-24 11:41
I have been looking at this, and in the words of Google: "It is _really_, _really_ hard".

What I found was that **harfbuzz** JUST does text **SHAPING** - this means that you have to provide it with a string that only contains a single script (Arabic OR Japanese) and a single direction (top-down OR right-to-left). As soon as you mix them, the shaper cannot correctly provide the position. I created a sample that could write text that contains only a single language.

To handle complex string, such as mixed scripts or directions, or even if the text is wrapped or not, we need to use a engine that can first break down the text into chunks, and then pass that off to harfbuzz. One such engine is ICU, which also needs to be included. This is a fairly large library (~5MB).

As a result, RTL text support is a bit more complex to add than a few extra methods. I also need to do more research into how to do this properly. I am thinking that rather than sticking everything into SkiaSharp (no need to add extra overhead just for text), we can rather do a separate library (eg: Mono.Harfbuzz and Mono.ICU) and then those libraries can be used by anyone that needs them. We can then write some "glue" that contains helper classes and extension methods so that all the hard work appears as a single method...

**Comment by mattleibow** [comment] 2017-04-24 11:48
@roceh  About the size, you are partially correct... Harfbuzz is quite small (~300KB), so that is OK, but ICU is the big one.

**Comment by migueldeicaza** [comment] 2017-04-25 15:31
I believe from looking at the samples that we only need to bind the APIs I described.   

That said, the native library would have to be compiled with ICU/Harfuzz, which is where the size increase would come.   I do not know how we can split that easily into a separate library.

**Comment by roceh** [comment] 2017-04-26 14:05
perhaps a basic/small custom ICU data blob could be included with the default SkiaSharp (I think this is most of the 5MB for the ICU library). And then another more complete ICU data blob that supports more locales in another nuget. No idea how easy it would be to redirect ICU to use another location for its data files. 

Reading this:
http://userguide.icu-project.org/icudata#TOC-Customizing-ICU-s-Data-Library
implies it might be possible.

**Comment by mattleibow** [comment] 2017-04-28 16:40
Here is a sample that you may like :)

<img width="480" alt="screen shot 2017-04-28 at 12 36 49 pm" src="https://cloud.githubusercontent.com/assets/1096616/25538206/c414314a-2c0f-11e7-8277-db8be6cf7aa7.png">

**Comment by mattleibow** [comment] 2017-05-01 18:44
I have merged the HarfBuzz support into master so SkiaSharp can now do text shaping properly with either the simple extension method `SKCanvas.DrawShapedText(...)`, a more detailed `SKShaper` instance, or by using HarfBuzz directly via the new HarfBuzzSharp binding.

_note: the shaper and extension method live in the `SkiaSharp.HarfBuzz` namespace so that other shapers can be added later if need be._

I am closing this issue as I believe I have addressed the issue here: adding proper RTL support. New issues can be created for new features, bugs or suggestions to avoid one long issue with all issues.

**Closed by mattleibow** 2017-05-01 18:44 UTC
Labels: enhancement, help wanted

**Comment by mattleibow** [comment] 2017-05-01 19:02
More advanced text support can be seen using WebKit's text stack:
https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/platform/fonts

**Comment by mattleibow** [comment] 2019-01-17 04:37
@sharpwood you just need to install the `SkiaSharp.HarfBuzz` NuGet package: https://nuget.org/packages/SkiaSharp.HarfBuzz

**Comment by EngMaream** [comment] 2020-02-06 14:54
why don't the Arabic letters appear ?
private void SKCanvasView_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs args)
        {
            SKImageInfo info = args.Info;
            SKSurface surface = args.Surface;
            SKCanvas canvas = surface.Canvas;

            canvas.Clear();

            using (SKPaint textPaint = new SKPaint
            {
                Style = SKPaintStyle.Stroke,
                Color = SKColors.Blue,
                StrokeWidth = 0.1f,
                StrokeJoin = SKStrokeJoin.Round
            })
            {
                SKRect textBounds = new SKRect();
                textPaint.MeasureText("ك", ref textBounds);

                // Inflate bounds by the stroke width
                textBounds.Inflate(textPaint.StrokeWidth / 2,
                                   textPaint.StrokeWidth / 2);

                canvas.Scale(info.Width / textBounds.Width,
                             info.Height / textBounds.Height);
                canvas.Translate(-textBounds.Right, -textBounds.Top);

                canvas.DrawText("ك", 0, 0, textPaint);
            }
        }

**Comment by mattleibow** [comment] 2020-02-06 15:38
@EngMaream, have a look at this snippet: https://github.com/mono/SkiaSharp/issues/272#issuecomment-298000023

Most probably you have a font that does not have Arabic text characters - since you are not setting any typeface. But I would also have a look at this for drawing text: https://github.com/toptensoftware/RichTextKit

That will allow you to actually create all the text you want, and then draw without having to measure and things.

**Comment by EngMaream** [comment] 2020-02-06 17:49
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SKCanvas' does not contain a definition for 'DrawShapedText' and no accessible extension method 'DrawShapedText' accepting a first argument of type 'SKCanvas' could be found (are you missing a using directive or an assembly reference?)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SKShaper' could not be found (are you missing a using directive or an assembly reference?)	

`        private void SKCanvasView_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs args)
        {
            SKSurface surface = args.Surface;
            SKCanvas canvas = surface.Canvas;

            canvas.Clear();

            using (var tf = SKFontManager.Default.MatchCharacter('א'))
            using (var shaper = new SKShaper(tf))
            using (var paint = new SKPaint { TextSize = 64, Typeface = tf })
            {
                canvas.Clear(SKColors.White);
                canvas.DrawShapedText(shaper, "אמת", 100, 200, paint);
            }
        }`
@mattleibow

**Comment by EngMaream** [comment] 2020-02-06 17:53
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SKCanvas' does not contain a definition for 'DrawShapedText' and no accessible extension method 'DrawShapedText' accepting a first argument of type 'SKCanvas' could be found (are you missing a using directive or an assembly reference?)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SKShaper' could not be found (are you missing a using directive or an assembly reference?)	

`        private void SKCanvasView_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs args)
        {
            SKSurface surface = args.Surface;
            SKCanvas canvas = surface.Canvas;

            canvas.Clear();

            using (var tf = SKFontManager.Default.MatchCharacter('א'))
            using (var shaper = new SKShaper(tf))
            using (var paint = new SKPaint { TextSize = 64, Typeface = tf })
            {
                canvas.Clear(SKColors.White);
                canvas.DrawShapedText(shaper, "אמת", 100, 200, paint);
            }
        }`
@mattleibow

**Comment by EngMaream** [comment] 2020-02-06 17:55
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SKCanvas' does not contain a definition for 'DrawShapedText' and no accessible extension method 'DrawShapedText' accepting a first argument of type 'SKCanvas' could be found (are you missing a using directive or an assembly reference?)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SKShaper' could not be found (are you missing a using directive or an assembly reference?)	

`        private void SKCanvasView_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs args)
        {
            SKSurface surface = args.Surface;
            SKCanvas canvas = surface.Canvas;

            canvas.Clear();

            using (var tf = SKFontManager.Default.MatchCharacter('א'))
            using (var shaper = new SKShaper(tf))
            using (var paint = new SKPaint { TextSize = 64, Typeface = tf })
            {
                canvas.Clear(SKColors.White);
                canvas.DrawShapedText(shaper, "אמת", 100, 200, paint);
            }
        }`
@mattleibow

**Comment by Gillibald** [comment] 2020-02-06 17:58
You need to install `SkiaSharp.HarfBuzz` to be able to use `DrawShapedText`

**Comment by EngMaream** [comment] 2020-02-06 18:00
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SKCanvas' does not contain a definition for 'DrawShapedText' and no accessible extension method 'DrawShapedText' accepting a first argument of type 'SKCanvas' could be found (are you missing a using directive or an assembly reference?)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SKShaper' could not be found (are you missing a using directive or an assembly reference?)	

`        private void SKCanvasView_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs args)
        {
            SKSurface surface = args.Surface;
            SKCanvas canvas = surface.Canvas;

            canvas.Clear();

            using (var tf = SKFontManager.Default.MatchCharacter('א'))
            using (var shaper = new SKShaper(tf))
            using (var paint = new SKPaint { TextSize = 64, Typeface = tf })
            {
                canvas.Clear(SKColors.White);
                canvas.DrawShapedText(shaper, "אמת", 100, 200, paint);
            }
        }`
@mattleibow

**Comment by eman1986** [comment] 2020-07-27 16:31
if I use DrawShapedText with numbers, I get a boxes back, is there something special I need to do for cases where a label would have text and numbers?

**Comment by Gillibald** [comment] 2020-07-27 17:39
By default harfbuzz just checks the first codepoint for directional properties. It might be possible that the text is shaped with LeftToRight direction because of that. Ideally text is split into runs of same direction before shaping. For advances scenarios you have to use HarfBuzzSharp directly.

**Comment by mattleibow** [comment] 2020-07-27 22:26
There are also 2 libraries that I know about that you might also be able to use and do all the work for you:
 - https://github.com/toptensoftware/RichTextKit
 - https://github.com/wouterst79/SkiaSharp.TextBlocks

**Comment by eman1986** [comment] 2020-07-28 01:46
Thanks for the resources, I'll probably give the second one a try as I need it to work with Xamarin and the first one doesn't look like it does.

**Comment by mattleibow** [comment] 2020-07-28 06:18
@eman1986 the docs are out of date. The first actually does and is what powers Comet.

But they both do the same thing so it doesn't really matter.

**Comment by Gillibald** [comment] 2020-07-28 08:14
I must disagree RichTextKit is the only library that implements some parts of the unicode standard. Full BiDi, line breaking algorithm, etc.

**Comment by mattleibow** [comment] 2020-07-28 11:30
Ah, thanks for that info. I didn't know about that.

Well, I guess @eman1986 has the answer now 😉 Use RichTextKit.

**Comment by eman1986** [comment] 2020-07-28 13:26
I'll give it a try then
