### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by hulluP** [mono/SkiaSharp#974] opened 2019-10-01 09:32 UTC
**Description**

skia does not render [svg](https://github.com/hulluP/SkiaSVGIssue/blob/master/debugSVG/demo.svg) correctly. 

**Code**

            SKCanvas canvas = args.Surface.Canvas;
            canvas.Clear();
            using (Stream stream = GetType().Assembly.GetManifestResourceStream("debugSVG.demo.svg"))
            {
                SKSvg svg = new SKSvg();
                svg.Load(stream);
                canvas.DrawPicture(svg.Picture);
            }
**Expected Behavior**

expected would be that following [https://github.com/hulluP/SkiaSVGIssue/blob/master/debugSVG/demo.svg](https://github.com/hulluP/SkiaSVGIssue/blob/master/debugSVG/demo.svg)

**Actual Behavior**

when the image loads it is missing the last path 
![Screenshot 2019-10-01 at 10 23 06](https://user-images.githubusercontent.com/46395952/65950560-962abf80-e43e-11e9-9af8-954df23f32ec.png)

**Basic Information**

- Version with issue:  1.68
- Last known good version: --
- IDE:  Visual Studio for Mac 
- Platform Target Frameworks: 
  - Android: 28
  - iOS:  13
 
**Screenshots**

see above

**Reproduction Link**

git: https://github.com/hulluP/SkiaSVGIssue

**Comment by daltonks** [comment] 2019-10-01 14:37
Opening the SVG in Inkscape, I see that the left-most part has an undefined fill color. Maybe SkiaSharp takes this to mean transparent instead of black?

As a workaround, I bet you could explicitly set a black fill color for the second path in the SVG.

**Comment by daltonks** [comment] 2019-10-01 14:40
Oh actually, when a fill is undefined, it looks like SkiaSharp holds on to the last fill color that was used instead of using black.

In this case, red is used because it was the fill color for the previous path in the SVG.

**Comment by hulluP** [comment] 2019-10-02 06:22
a pointer here to maybe speed up the triage:
When I load the image as a FFImageLoading.CachedImage it shows correctly. The FFImageLoading framework is using skia.

**Comment by mattleibow** [comment] 2019-11-05 21:56
@hulluP I believe that FFImageLoading is using it's own implementation of the SVG. Currently, there is not much work going on with the SkiaSharp SVG due to priorities.

I have not tried this particular set of libraries, but you could check out https://github.com/wieslawsoltes/Svg.Skia

@wieslawsoltes has been hard at work here and has some good bits that probably can do a far better job than SkiaSharp could ever do.

Duplicate of https://github.com/mono/SkiaSharp.Extended/issues/2

**Closed by mattleibow** 2019-11-05 21:56 UTC

**Comment by wieslawsoltes** [comment] 2019-11-06 19:38
@hulluP @mattleibow I am working hard on the `Svg.Skia` library. 

There has been some great progress with `Svg` library itself https://github.com/vvvv/SVG

Here is sample test app I am using in development. You can check easily your `SVG` with this tool (and compare with Chrome rendering):

https://github.com/wieslawsoltes/Svg.Skia/tree/master/tests/SvgToPng

There is still a lot work to be done 😄

**Comment by hulluP** [comment] 2019-12-31 07:12
@wieslawsoltes @mattleibow 
I tried to plug in the svg.skia but I am failing to load any type of files. I tried multiple ways but I am getting a "System.PlatformNotSupportedException has been thrown".
my simple sample project is at https://github.com/hulluP/SkiaSVGIssue any pointers how to get the svgs to render are greatly appreciated. 

thanks HP

**Comment by wieslawsoltes** [comment] 2019-12-31 07:51
> @wieslawsoltes @mattleibow
> I tried to plug in the svg.skia but I am failing to load any type of files. I tried multiple ways but I am getting a "System.PlatformNotSupportedException has been thrown".
> my simple sample project is at https://github.com/hulluP/SkiaSVGIssue any pointers how to get the svgs to render are greatly appreciated.
> 
> thanks HP

Toy need to use one of support target frameworks for final executable netcoreapp2.2 or newer and net452 or newer. The nestadndard2.0 will not work if final executable does not use supported target framework. This is known issue.

**Comment by mattleibow** [comment] 2019-12-31 11:58
Thanks @wieslawsoltes .

@hulluP I would suggest opening an issue on Svg.Skia so that not only can the issue be tracked, but it will get implemented. I am hoping @wieslawsoltes supports iOS and Android? Since SkiaSharp is cross-platform.

**Comment by wieslawsoltes** [comment] 2019-12-31 12:28
> Thanks @wieslawsoltes .
> 
> @hulluP I would suggest opening an issue on Svg.Skia so that not only can the issue be tracked, but it will get implemented. I am hoping @wieslawsoltes supports iOS and Android? Since SkiaSharp is cross-platform.

It's issue with dependency `System.Drawing.Common` and missing stuff when using `.NETStandard 2.0` and using different executable than netcoreapp2.2 or newer and net452 or newer.

Svg.Skia depends on https://github.com/vvvv/SVG and it depends on `System.Drawing.Common`.

https://github.com/vvvv/SVG/issues/581

Probably some stuff is missing in `System.Drawing.Common` or other related issue with this package on Android/iOS.

**Comment by wieslawsoltes** [comment] 2019-12-31 15:35
This is how Svg.Skia renders demo.svg file:
![SvgToPng_2019-12-31_16-34-49](https://user-images.githubusercontent.com/2297442/71626070-92e4d280-2beb-11ea-992f-8cfec3de3474.png)
