### ISSUE TITLE
Enable stylus features with Forms Touch events [FEATURE] 

### ISSUE THREAD

**Issue by mscherotter** [mono/SkiaSharp#1201] opened 2020-03-30 02:26 UTC
**Is your feature request related to a problem? Please describe.**
Add pressure, orientation, and button/eraser identification to SKCanvasView Touch events.

**Describe the solution you'd like**
Change the code in the SKTouchHandler to pass the pressure, button, and orientation of touch events coming from stylus.

**Describe alternatives you've considered**
None known

**Additional context**

**Comment by mattleibow** [comment] 2020-03-30 09:00
This looks like a duplicate of #1186?

Closing this one.

**Closed by mattleibow** 2020-03-30 09:00 UTC
Labels: type-duplicate
