### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by KingSora** [mono/SkiaSharp#179] opened 2016-10-29 20:47 UTC
Hello!

I can't build the project on windows with the bootstrapper.ps1 script.
Here is a screen of the errors I get:

http://puu.sh/rZTuo/0ae38eaa8d.png

Hopefully someone can help me.

Best regards,
Sora

**Comment by mattleibow** [comment] 2016-11-01 09:59
I had a look and I believe it is because you are using PowerShell version 2, and we wrote the script for v3. I fixed that issue in fd88f1add7954b3d428e9bcf251b8d064080ebca

Let me know how things go.

Also remember that you don't have to build SkiaSharp to use the samples. Right now the code that will work out the box is v1.54.1: https://github.com/mono/SkiaSharp/releases/tag/v1.54.1

The master is the almost-finished bits for the next v1.55 - the samples want the later version of the NuGet, so you will have to build everything, but the samples in v1.54.1 will work with the v1.54.1 NuGet.

**Comment by mattleibow** [comment] 2016-11-04 02:51
@KingSora I am closing this now as I confirmed that I can build SkiaSharp on Powershell v2. Please re-open if you are still having issues.

**Comment by KingSora** [comment] 2016-11-05 15:07
Thank you very much!

This error is resolved, but there is a new one now.
http://puu.sh/s7lWF/f499ce4e56.png

The error says: "The file externals-uwp couldn't be found".

Best regards,
Sora

**Comment by mattleibow** [comment] 2016-11-07 14:28
@KingSora, I think I may know what is happening here. Did you clone the submodules too?

    git submodule update --init --recursive

The submodules are skia and the build tools to actually compile all those pieces. SkiaSharp is just the managed wrapper, and we use MSBuild for that. skia is a lot of C/C++ code, and we just build the library using Google tools.

You can check to see it the submudules are downloaded under the `externals` folder, there should be `skia` and `depot_tools` folders with lots of files.

**Comment by KingSora** [comment] 2016-11-07 14:44
Yes they are cloned, I tried a lot by myself but I really dont know why it wont work.

**Comment by KingSora** [comment] 2016-11-07 15:18
FINALLY! After really long time I found the mistake!

I've two harddrives and my Python2.7 Path wasn't correct anymore If I hadn't plugged in my D: drive.
Maybe I should watch more carefully on the Path variables I've registred on my machine.

You can close it now.

**Comment by mattleibow** [comment] 2016-11-07 15:40
Hehe. Those little things. Have fun!

**Closed by mattleibow** 2016-11-07 15:40 UTC
Labels: bug, enhancement
