### ISSUE TITLE
TypeInitializationException occuring in ASP.Net MVC, only in Azure

### ISSUE THREAD

**Issue by MathieuJack** [mono/SkiaSharp#1861] opened 2021-11-11 09:47 UTC
I have a ASP.NET MVC website project that uses Skiasharp.
It is working well locally.
Recently I tried to publish it to Azure. When running from Azure, this website generates an exception at startup:

The version of the native libSkiaSharp library (80.2) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.0, 89.0).

 My whole solution is using v2.80.3
ASP.Net MVC project itself references:
  <package id="SkiaSharp" version="2.80.3" targetFramework="net47" />
  <package id="SkiaSharp.Views.Desktop.Common" version="2.80.3" targetFramework="net47" />

ASP.Net MVC project references library projects that reference nugets (if I write the union of all projects):
- SkiaSharp 
- Skiasharp.Views
- Skiasharp.Views.Desktop.Common
- SkiaSharp.Views.Forms
- SkiaSharp.Views.GTK2
- SkaSharp.Views.WindowsForms
- SkiaSharp.Views.WPF

all in v2.80.3

**Comment by YoshiRulz** [comment] 2022-05-22 10:07
Duplicate of #1715?

**Comment by YoshiRulz** [comment] 2022-08-13 03:51
https://github.com/mono/SkiaSharp/issues/1715#issuecomment-1213452978:
> This was fixed in a later version. Either try the 2.80.4 patch or even better the new 2.88.x versions.

**Comment by mattleibow** [comment] 2022-08-13 17:09
It has been a long time, so closing this as all the latest versions of things should now be doing the right things.

**Closed by mattleibow** 2022-08-13 17:09 UTC
