### ISSUE TITLE
[FEATURE] Support Blazor Desktop

### ISSUE THREAD

**Issue by IvanJosipovic** [mono/SkiaSharp#1834] opened 2021-10-17 23:30 UTC
I would like to use the package SkiaSharp.Views.Blazor with Blazor Desktop.

When I try using this library in Blazor Desktop, the following error is shown, "(SkiaSharp currently only works on Web Assembly.)"

**Comment by mattleibow** [comment] 2021-10-18 01:43
Interesting... So the Blazor right now only is on wasm, but this is another case where we probably want to use the native apis instead of Web apis...

I will see what I can do.

**Comment by mattleibow** [comment] 2021-10-18 05:10
@eilon what is the story here? I suppose I expected IJSInProcessRuntime to be available on Blazor desktop/mobile since it all exists in a single process on the device.

Should it be? Is this a bug or is there another JS runtime type I should use?

**Comment by SteveSandersonMS** [comment] 2022-06-13 09:11
For clarification, the only difference between `IJSRuntime` and `IJSInProcessRuntime` is that `IJSInProcessRuntime` supports synchronous calls. As such,

 * Platforms that can offer synchronous calls should offer `IJSInProcessRuntime`
 * Platforms that cannot (i.e., only support async interop calls) should offer `IJSRuntime`

As for Blazor Hybrid, the web view we're using is WebView2. **WebView2 only supports async interop calls via its `ExecuteScriptAsync` API**. There isn't a synchronous API. So, it is correct and by design that Blazor should only offer `IJSRuntime` when running on WebView2.

However, I can't think of any particular reason why SkiaSharp shouldn't be able to work on top of `IJSRuntime` via async calls. At least in the case of Blazor Hybrid, these async calls aren't going over a network, so they will be delivered approximately instantly even if they have a large payload.

If you think there are technical reasons why it's not possible to dispatch SkiaSharp's calls over `IJSRuntime`, I'd love to hear more details and maybe we can help figure out a way!

**Comment by RChrisCoble** [comment] 2022-06-13 14:39
Thanks you @SteveSandersonMS!  

@mattleibow, is using IJSRuntime viable with SkiaSharp?  Is this something you can evaluate/POC?

**Comment by danroth27** [comment] 2022-06-15 15:48
> @danroth27 I am wondering if you have a link to the issue you mentioned about the other issue where Blazor WASM and Blazor server conflict as of net6.0 and only work with major hacks. And if there is any issues for the support of this for net7.

https://github.com/dotnet/aspnetcore/issues/38128

**Comment by IvanJosipovic** [comment] 2022-06-15 19:12
I would find it useful if I could use it in WASM, Desktop and MAUI. This thread is making me feel that we have some fundamental gaps in the architecture of the Blazor Hybrid model and its disappointing.

**Comment by danroth27** [comment] 2022-06-15 19:34
I've opened https://github.com/dotnet/aspnetcore/issues/42216 to discuss how we want to handle this scenario on the Blazor side.

**Comment by mattleibow** [comment] 2022-06-15 20:09
Closing this issue now as it basically is not on SkiaSharp to render pictures in the embedded webviews because just like with blazor server, there is no way for skiasharp to access memory across the network or across the process boundary - since the "embedded webviews" are really just windows into another running process.

Hopefully the issue Daniel opened allows us to come up with a better client-server architecture. And the issue for running WASM in a server scenario will also help.

**Closed by mattleibow** 2022-06-15 20:09 UTC
