### ISSUE TITLE
WinUI .Net Maui and GPU / OpenGL 

### ISSUE THREAD

**Issue by FingerMoonSoftware** [mono/SkiaSharp#2355] opened 2023-01-06 20:33 UTC
I've been reading different articles on the subject, and my take away is that Maui with WinUI cannot yet work with GPU accelerated graphics. I'm currently trying to port a game my company has been writing from Xamarin to Maui. I can't seem to get the SKGLView to work. It's giving me an error of a missing handler. I added the code to the main MauiProgram builder .UsinSkiaSharp(true) to no avail.

Is this still a current issue or is it that I'm doing something wrong?
Is OpenTK an option?
Or maybe Win2D?
The game would run far too slowly without acceleration. 
Any help is appreciated.

The game demo is currently available on the Microsoft Marketplace for testing.

Since we're all developers here, I'll leave the link to it with using Xamarin.

https://www.microsoft.com/store/apps/9P5QG567VSFK

**Comment by marcojak** [comment] 2023-02-19 20:05
I'm interested as well at the gpu acceleration with MAUI.
I'm working on a desktop application for Windows and Mac.
Right now the performances are barely acceptable and I'm 100% that moving from CPU to GPU would solve the issue.
It would be great to know if there are plans to enable gpu acceleration or if this is just a lost hope.

**Comment by mattleibow** [comment] 2023-09-06 14:36
Duplicate of #1893

**Closed by mattleibow** 2023-09-06 14:36 UTC
