### ISSUE TITLE
[BUG] SKXamlCanvas in Winui3  bug after Visual studio Update

### ISSUE THREAD

**Issue by chaibi-mustapha** [mono/SkiaSharp#3031] opened 2024-10-05 20:13 UTC
### Description

a debugger is attached but not configured to debug this exception

### Code

```
Code Xaml :

<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="AppTest5.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AppTest5"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:skia="using:SkiaSharp.Views.Windows"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <skia:SKXamlCanvas  x:FieldModifier="public"  x:Name="skXamlCanvas"  
                                  Width="1024"  Height="1024"
                                  HorizontalAlignment="Stretch"  VerticalAlignment="Stretch"
                                  />
    </StackPanel>
</Window>

```
Code C# :

```
using Microsoft.UI.Xaml.Navigation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace AppTest5
{
    /// <summary>
    /// An empty window that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
        }

    }
}

```

### Version of SkiaSharp

2.88.8 (Current)

### Last Known Good Version of SkiaSharp

2.88.7 (Previous)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Relevant Screenshots

![SkiaSharp Bug](https://github.com/user-attachments/assets/b25672c6-aca9-4376-9dea-91cab65a2a7d)
![image](https://github.com/user-attachments/assets/994929a0-dabd-49bd-8358-011b7918b7f8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mangepange** [comment] 2024-10-09 08:54
This is the same crash as when updating to WinUI 1.6.0 (#2999).
It seems like the latest version of VS (17.11.5) updates the version of CsWinRT to 2.1.2. And from what I've seen, the issue is related to changes made in CsWinRT v2.1.1.

**Comment by christoroth** [comment] 2024-10-09 11:29
Btw, this is also occurring in Windows based .Net Maui apps that use skia sharp.  Updated Visual Studio and therefore also the windows sdk and my app started to crash but only in Windows (Android is ok).  

Created a brand new Maui project and ran it from the default code that counts button clicks.  Added SkiaSharp (remembering to add the UsesSkiaSharp call to MauiProgram.cs) and adding the SkCanvasView to the mainpage.xaml introduces the crash:

`<skia:SKCanvasView x:Name="skCanvasView" WidthRequest="30" HeightRequest="50" BackgroundColor="Red" />`

**Comment by TopperDEL** [comment] 2024-10-11 08:47
I have the same issue. From my point of view the only change between a working version and a crashing version is the switch from .Net SDK 8.0.402 to 8.0.403. It now crashes locally and with the version build in a Github Action. The only difference in the pipeline is the switch in the SDK-version. Don't know if this is really related, though. My app silently crashes without any exception if the `SkXamlCanvas` comes into view (this is an Uno app).

**Comment by TopperDEL** [comment] 2024-10-11 09:16
This seems to be the StackTrace:

   ```
bei System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   bei System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   bei WinRT.IWinRTObject.<IsInterfaceImplementedFallback>g__GetObjectReferenceViaVftbl|1_1(IObjectReference objRef, Type vftblType) in WinRT\IWinRTObject.cs: Zeile204
   bei WinRT.IWinRTObject.IsInterfaceImplementedFallback(RuntimeTypeHandle interfaceType, Boolean throwIfNotImplemented) in WinRT\IWinRTObject.cs: Zeile192
   bei WinRT.IWinRTObject.System.Runtime.InteropServices.IDynamicInterfaceCastable.IsInterfaceImplemented(RuntimeTypeHandle interfaceType, Boolean throwIfNotImplemented) in WinRT\IWinRTObject.cs: Zeile30
   bei WinRT.CastExtensions.As[TInterface](Object value) in WinRT\CastExtensions.cs: Zeile17
   bei SkiaSharp.Views.Windows.Utils.GetByteBuffer(IBuffer buffer)
   bei SkiaSharp.Views.Windows.WindowsExtensions.GetPixels(WriteableBitmap bitmap)
   bei SkiaSharp.Views.Windows.SKXamlCanvas.CreateBitmap(SKSizeI& unscaledSize, Single& dpi)
   bei SkiaSharp.Views.Windows.SKXamlCanvas.DoInvalidate()
   bei ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr thisPtr) in ABI.Microsoft.UI.Dispatching\DispatcherQueueHandler.cs: Zeile123
```

**Comment by christoroth** [comment] 2024-10-11 09:22
3.0.0-preview-5.3 from package source https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json stopped the crashes for me in my test app so I have temporarily done the same in the app I'm developing until 3.0.0 is formally released (hopefully before my deadline!!).

**Comment by TopperDEL** [comment] 2024-10-11 09:31
Yes, just found out - this is the correct issue: https://github.com/mono/SkiaSharp/issues/2999

**Comment by Mangepange** [comment] 2024-10-14 09:37
We were able to solve this by adding a specific WindowSDK package version in our project files:

<WindowsSdkPackageVersion>10.0.22621.34</WindowsSdkPackageVersion>

Versions from .38 and above does not work for us (that's the version that WinUI 1.6.0 requires btw).

**Comment by tdoell** [comment] 2024-10-14 16:02
@christoroth Thanks for providing that package source link and such. I have upgraded our project we are currently converting to .NET MAUI and that has fixed our app from crashing this morning. Thanks!

**Comment by john-hollander** [comment] 2024-10-23 11:59
> We were able to solve this by adding a specific WindowSDK package version in our project files:
> 
> `<WindowsSdkPackageVersion>10.0.22621.34</WindowsSdkPackageVersion>`
> 
> Versions from .38 and above does not work for us (that's the version that WinUI 1.6.0 requires btw).

I'll try this, but it's only a temporary workaround.

All you need to reproduce in MAUI is to run in Windows with an SKCanvasView in a page, like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:AspectTextSizingTest"
             xmlns:sk="clr-namespace:SkiaSharp.Views.Maui.Controls;assembly=SkiaSharp.Views.Maui.Controls"
             x:Class="AspectTextSizingTest.MainPage">

    <Grid>
        <sk:SKCanvasView />
    </Grid>
</ContentPage>
```

And note that .UseSkiaSharp() is in the builder:

 ```
   public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseSkiaSharp()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });

            return builder.Build();
        }
    }
```

**Comment by john-hollander** [comment] 2024-10-23 22:08
> 3.0.0-preview-5.3 from package source https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json stopped the crashes for me in my test app so I have temporarily done the same in the app I'm developing until 3.0.0 is formally released (hopefully before my deadline!!).

Thanks for this. It looks like it works on my end as well. Hopefully we'll get this in the main preview stream soon.

For anyone else reading, add the package source to NuGet in the settings in the top-right corner of the NuGet window in Visual Studio, where the package sources are listed.

**Comment by mattleibow** [comment] 2024-10-25 16:30
Closing this for now as the issue is fixed for both v2 and v3 in the latest preview.

**Closed by mattleibow** 2024-10-25 16:30 UTC
Labels: type/bug
