### ISSUE TITLE
DrawImage doesn't work properly with SKFilterQuality.High

### ISSUE THREAD

**Issue by Rungee** [mono/SkiaSharp#282] opened 2017-04-26 19:33 UTC
The issue has already been posted on [google groups](https://groups.google.com/forum/#!topic/skia-discuss/7xcKq09kL0Y).

**Comment by mattleibow** [comment] 2017-04-27 18:38
I was not able to reproduce this.

I loaded my image like this (I load it via a bitmap because I am lazy):

```csharp

var assembly = GetType().GetTypeInfo().Assembly;
using (var stream = assembly.GetManifestResourceStream("SkiaSharpXamarinFormsDemo.image.png"))
{
	bitmap = SKBitmap.Decode(stream);
	image = SKImage.FromBitmap(bitmap);
}
```

Then, in my draw event, I draw:

```csharp
canvas.Clear(SKColors.Blue);
var paint = new SKPaint { FilterQuality = SKFilterQuality.High };
canvas.DrawImage(image, SKRect.Create(300, 300), paint);
```

Is it possible to provide a small test case or code that reproduces the problem?

![image](https://cloud.githubusercontent.com/assets/1096616/25498326/dd4976bc-2b87-11e7-8ed2-30b826df5b08.png)

**Comment by Rungee** [comment] 2017-04-27 19:21
In the post, there was a link to a [GitHub repository](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FRungee%2FSkiasharp_Tests&sa=D&sntz=1&usg=AFQjCNFh3Lgk0gq78p0dtgT0le7sSBzZfg) containing a test case.

It is important to note that this bug happens only under certain conditions such as image scale or rect coordinates.

**Comment by mattleibow** [comment] 2017-04-28 07:32
All right! I am now able to reproduce it. It appears that when the image has a negative X and Y, the transparency is lost...

Not sure why yet, but I will have a look and see if this is a bug that was fixed in a later version of skia.

**Comment by mattleibow** [comment] 2017-05-11 18:25
@Rungee I think I have found the problem.

There appears to be a bug in skia that doesn't draw Unpremultiplied images correctly. When using `SKBitmap.Decode(path/stream)`, the image is decoded as Unpremultiplied. To decode as a Premultiplied image, use the overload that allows you to specify the desired alpha type:

```csharp
using (var codec = SKCodec.Create(new SKFileStream(path)))
{
    var info = new SKImageInfo(codec.Info.Width, codec.Info.Height);
    var image = SKImage.FromBitmap(SKBitmap.Decode(codec, info));
    
    // draw
}
```

This is almost what we do under the hood, but instead of creating a new `SKImageInfo`, I use the one provided by the codec - which is Unpremultiplied.

**Comment by mattleibow** [comment] 2017-05-11 18:27
I noticed on the linked issue that they pointed to a forum post: https://forums.xamarin.com/discussion/88793/scaling-transparent-png-images

There I suggested the same solution.

**Comment by mattleibow** [comment] 2017-05-11 19:42
According to Google (https://groups.google.com/forum/#!topic/skia-discuss/7xcKq09kL0Y), I should be able to always use Premul when decoding since it really is the only type supported:

> Skia only supports drawing premultiplied bitmaps/images. 

So I am thinking of changing the default alpha type when decoding... Any thoughts?

**Comment by mattleibow** [comment] 2017-05-12 02:35
I am closing this because:
 - it is most probably a bug inside skia (according to Google)
 - I have merged a PR that should default to an alpha type that will work in most cases
 - `SKBitmap` is really a dying type (sloooowly), `SKImage` is preferred
 - `SKImage.FromEncodedData` is probably the better way to decode

**Closed by mattleibow** 2017-05-12 02:35 UTC
