### ISSUE TITLE
[FEATURE] Binding Skottie

### ISSUE THREAD

**Issue by PieroCastillo** [mono/SkiaSharp#1580] opened 2021-01-15 20:48 UTC
Hello, I see on Skia Official Docs there is an Lottie Animation Player, [Skottie](https://skia.org/user/modules/skottie), and I wanna use this feature, but I saw the SkiaSharp API and this doesn't exist, do you think implement this module some day? or never? if so I would like to know why.

**Comment by mattleibow** [comment] 2022-05-28 13:44
Duplicate of #661

**Closed by mattleibow** 2022-05-28 13:44 UTC
