### ISSUE TITLE
[BUG] Corrupted Image when loading from network stream. It works fine in 2.82.0, It has issues in 2.83.0 and 2.88.0-preview.232

### ISSUE THREAD

**Issue by bymin** [mono/SkiaSharp#1985] opened 2022-03-31 02:39 UTC
**Description**

It rendered corrupted image when loading from network stream. It works fine in 2.82.0, It has issues in 2.83.0 and the latest preview branch 2.88.0-preview.232

**Code**

     // Below is the complete test code in VS2022 on .NET 6

     using System.Net;
     using SkiaSharp;

     await DownloadTile("https://tile.openstreetmap.org/1/0/0.png", @"d:\test\test.png");

     static async Task DownloadTile(string uri, string path)
      {
 
      HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);
      request.Method = "GET";
      request.UserAgent = "agent";
  
      using var webResponse = await request.GetResponseAsync();
      await using var input = webResponse.GetResponseStream();
  
      await using var output = File.Create(path);
      var bitmap = SKBitmap.Decode(input);
  
      using var skImage = SKImage.FromBitmap(bitmap);
      var skData = skImage.Encode(SKEncodedImageFormat.Png, 80);
      skData.SaveTo(output);
     }

**Expected Behavior**

The tile https://tile.openstreetmap.org/1/0/0.png is saved to d:\test\test.png

**Actual Behavior**

The tile generated in d:\test\test.png is corrupted, only part of the image can be seen.  V2.82.0 doesn't have this issue. 

**Basic Information**

- Version with issue:   2.83.0 and the latest preview branch 2.88.0-preview.232
- Last known good version:  2.82.0
- IDE:   Visual Studio  2022
- Platform Target Frameworks: Tested in .NET Framework 4.8 and .NET 6
- Target Devices:   Windows Console. 
  
<details>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

corrupted image: 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/15203030/160965126-01f545d5-94f6-492a-b27e-d4d7779dbb88.png">

**Reproduction Link**

**Comment by inforithmics** [comment] 2022-03-31 07:06
I think it could be the same issue as this.

https://github.com/mono/SkiaSharp/issues/1981

**Comment by bymin** [comment] 2022-03-31 14:43
@inforithmics yep, they look like the same.

**Comment by mattleibow** [comment] 2022-05-17 04:22
Duplicate of #1981

**Closed by mattleibow** 2022-05-17 04:22 UTC
