### ISSUE TITLE
[BUG] SKRuntimeEffect compilation is missing build-in functions

### ISSUE THREAD

**Issue by Oribow** [mono/SkiaSharp#1868] opened 2021-11-18 23:45 UTC
**Description**

I've been trying out the new SKRuntimeEffect support in 2.88.0-preview.155 . Compilation of shaders using some opengl functions fails. (Tested with step and smoothstep). Not sure if this a skiasharp problem or a skia problem.

**Code**

```
uniform float2 iResolution; 
uniform float2 iPos; 

half4 main(float2 fragcoord) {
  float2 uv = (fragcoord - sk_FragCoord.xy) / iResolution.y;
  float d = length(uv);
  float m = 0.03 / d;
  m *= step(0.2, 0.3);
  return half4(m, m, m, m);
}"
```

**Expected Behavior**

This should compile. The same code works on the skia-sksl demo [https://shaders.skia.org/](website).

**Actual Behavior**

Compilation outputs the following error:
`error: 9: unknown identifier 'step'`
This also happens with 'smoothstep'. Its weird that the 'length' function still works though. I have read that Skia only supports a subset of GL functions, but since it works on the demo site and these being very important shader functions, I doubt that they aren't included.

**Basic Information**

- Version with issue:  2.88.0-preview.155
- Platform Target Frameworks:
  - Android: 11 (API level 21)
  - Xamarin: 5.0.0.2244

**Comment by cyraid** [comment] 2023-05-24 15:37
It errors with 'round' as well.. I'm wondering if it's 'cause it's a bit older of Skia?

**Comment by mattleibow** [comment] 2023-08-05 06:55
Updating skia to the latest makes most of the functions work, however, the `sk_FragCoord` uniform is not actually available in the public spec. That is just for internal use by skia.

**Comment by mattleibow** [comment] 2023-08-05 06:55
Duplicate of https://github.com/mono/SkiaSharp/issues/2543

**Closed by mattleibow** 2023-08-05 06:55 UTC
