### ISSUE TITLE
[BUG] Error Rendering Text in a Loop using SKTextAlign

### ISSUE THREAD

**Issue by sremiger1** [mono/SkiaSharp#1449] opened 2020-08-06 17:16 UTC
**Description**

I get an Error Rendering Text in a loop, I have attached a zip file of the code to reproduce the error.  There are 2 parts Part 1 goes out and Renders text of 300 items and it fails to render when the Text align is set to Center.  The second part does it manually and it renders just fine.  

**Code**

Attached is the sample code.
[TestApp.zip](https://github.com/mono/SkiaSharp/files/5036608/TestApp.zip)

**Expected Behavior**

Expect rendering on Text align to not fail.

**Actual Behavior**
Strange Error message

**Basic Information**

- Version with issue:  2.80.1
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - Windows Classic:  10

An unhandled exception of type 'System.NullReferenceException' occurred in Unknown Module.
Object reference not set to an instance of an object. occurred  

**Screenshots**

Attached is the error received 
![image](https://user-images.githubusercontent.com/26170868/89561451-1ef05580-d7de-11ea-8602-ed6f1c551215.png)

**Reproduction Link**

Attached is the sample code.
[TestApp.zip](https://github.com/mono/SkiaSharp/files/5036608/TestApp.zip)

**Comment by mattleibow** [comment] 2020-08-07 22:23
Closing this as a duplicate of #1409

Not quite sure what is going on, but will be updating that issue.

**Closed by mattleibow** 2020-08-07 22:24 UTC
