### ISSUE TITLE
[BUG] Encoding/Decoding PNG image produces artifacts in the output after upgrading to SkiaSharp 2.88.0.

### ISSUE THREAD

**Issue by AlexNosk** [mono/SkiaSharp#2165] opened 2022-07-13 07:15 UTC
**Description**

After encoding/decoding PNG image, the output image has artifacts. Everything works fine in 2.80.1 version of SkiaSharp.
[images.zip](https://github.com/mono/SkiaSharp/files/9099831/images.zip)

**Code**

```cs
using SkiaSharp;

using SKBitmap bmp = SKBitmap.Decode(@"C:\Temp\image1.png");
using SKFileWStream output = new SKFileWStream(@"C:\Temp\out.png");
bmp.Encode(output, SKEncodedImageFormat.Png, 100);
```

**Basic Information**

- Version with issue:  2.88.0
- Last known good version:  2.80.1
- IDE:  VS 2022
  

**Screenshots**

![image](https://user-images.githubusercontent.com/31235892/178673004-07dc09f7-ce87-4d36-a0b5-c4a4138a11ce.png)

**Comment by jxlarrea** [comment] 2022-07-14 07:58
More reports of this bug here: https://github.com/mono/SkiaSharp/issues/2132

**Comment by mattleibow** [comment] 2022-08-13 19:05
Duplicate of #2095

**Closed by mattleibow** 2022-08-13 19:05 UTC
