### ISSUE TITLE
BadImageFormatException when creating image using SkiaSharp in ASP.NET Web application

### ISSUE THREAD

**Issue by MohanaselvamJ** [mono/SkiaSharp#579] opened 2018-07-13 15:14 UTC
### Description
Results BadImageFormatException when creating image using SkiaSharp library in ASP.NET Web application.

### Code
When creating image using in SKBitmap constructor
    public SKBitmap(int width, int height, bool isOpaque = false);

### Exeption detail
[BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)]
   SkiaSharp.SkiaApi.sk_colortype_get_default_8888() +0
   SkiaSharp.SKImageInfo..cctor() +7

[TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.]
   SkiaSharp.SKBitmap..ctor(Int32 width, Int32 height, Boolean isOpaque) +38

### Basic Information

- Version with issue:  1.60
- IDE:  Visual Studio 2017

**Comment by mattleibow** [comment] 2018-11-29 16:16
Duplicate of #513 
Duplicate of #572 

Basically, the Windows build, you have to pass the preferred architecture, or make sure you are not building AnyCPU and running on a different platform.

**Closed by mattleibow** 2018-11-29 16:16 UTC
