### ISSUE TITLE
[BUG] SkiaSharp.Views.Uno's SKXamlCanvas has a binary incompatibility with Uno 4 that causes page load failure

### ISSUE THREAD

**Issue by mikebmcl** [mono/SkiaSharp#1877] opened 2021-12-02 16:34 UTC
**Description**

In the new Uno Platform 4.0 release there were some binary compatibility breaks. One of them is that the signature for CoreDispatcher.RunAsync changed from `public UIAsyncOperation RunAsync(CoreDispatcherPriority priority, DispatchedHandler handler)` to `public IAsyncAction RunAsync(CoreDispatcherPriority priority, DispatchedHandler handler)`. 

The SkiaSharp.Views.Uno SKXamlCanvas control calls that method in its `public new async void Invalidate();` method when it is called or some action causes it to be called from any thread other than the UI thread; see: [SKXamlCanvas.cs line 122 (note: link is to the file as found in the last commit that modified it at the time I'm writing this)](https://github.com/mono/SkiaSharp/blob/4a687a87b86f127ccc23116ee410dcb5df8fca63/source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno/SKXamlCanvas.cs#L122) .

It was difficult to decide where to post this since the breaking change is in Uno Platform. However the breaking change brings it into conformance with the UWP API and this will likely be an ongoing problem for SkiaSharp (as explained below). On the surface it seems like all that needs to be done to make it work with Uno 4 is to create a new SkiaSharp.Views.Uno package built against Uno 4.

That said, this is probably going to be an ongoing problem for SkiaSharp since if it's compiled against Uno 4 then it will have the same missing method issue (except with the expected and actual signatures reversed) when someone tries to use it with Uno 3.X (or any other version of Uno prior to 4). So you may need to ship two versions, deprecate support for pre-Uno 4, and at some reasonable time in the future cease building new SkiaSharp packages for pre-Uno 4.

The exact commit where this change occurred is here: [unoplatform/uno github repo commit link - relevant file src/Uno.UWP/UI/Core/CoreDispatcher.cs - old line is 153; new line is 79](https://github.com/unoplatform/uno/commit/37a4058dfe5bd856ef2ec28a608fb02665f5af32#diff-717fd2832a596b5881048bdbabe36cd250b2e583f03f602b099398149f4d3bf7)

Lastly, I did not test the `SKSwapChainPanel` control and because I could not construct a `SKXamlCanvas` control I was unable to determine if there were other breakages besides the one that occurred in `SKXamlCanvas.Invalidate`

**Code**

In Visual Studio 2022, with the 'Uno Platform Solution Templates' extension installed, create a new 'Multi-Platform App (Uno Platform|Xamarin)' solution. When the solution is created, using nuget, do the following:

- Add the SkiaSharp package to all projects
- Add the SkiaSharp.Views package to the UWP project.
- Add the SkiaSharp.Views.Uno package to all of the projects except the UWP project.
 
Next, in MainPage.xaml, to the Page tag, add `xmlns:views="using:SkiaSharp.Views.UWP"`. Change the Page's Content control from `Grid` to `StackPanel` but leave the  "Hello, world!" `TextBlock` control. After that TextBlock control, add `<views:SKXamlCanvas />`.

Finally, in App.xaml.cs, in the `OnLaunched` method, modify the line

`                   rootFrame.Navigate(typeof(MainPage), args.Arguments);`

to 

`                    try
                    {
                        rootFrame.Navigate(typeof(MainPage), args.Arguments);
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"Exception type: {ex.GetType().FullName}.\nMessage: {ex.Message}\nStack Trace: {ex.StackTrace}");
                        System.Diagnostics.Debugger.Break();
                        throw;
                    }
`

**Expected Behavior**

Run any of the Platform projects via debugging in Visual Studio. The app will start properly and navigate to MainPage.xaml causing the text "Hello, world!" to be visible.

**Actual Behavior**

On any platform other than UWP, a `System.MissingMethodException` is thrown internally (it appears in the Output window's "Show output from: Debug" output) but does not directly propagate out to user code and thus cannot be caught. It does not crash the program and so the program continues to run.

After that, a `System.InvalidOperationException` is thrown that _is_ catchable that informs you of the MissingMethodException via its Message property, which contains a value along the lines of:

> Failed to load MyProject.MainPage: System.MissingMethodException: Method not found: 'Windows.UI.Core.UIAsyncOperation Windows.UI.Core.CoreDispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority, Windows.UI.Core.DispatchedHandler)'.
> at SkiaSharp.Views.UWP.SKXamlCanvas.Invalidate()
> ...

The debugger will catch that exception in the code we added in App.xaml.cs. After continuing run the program, the app will swallow the exception and display a blank window, i.e., no "Hello, world!" text, since it was unable to load MainPage.

**Basic Information**

- Version with issue:  All versions built before Uno Platform 4, which is currently all versions.
- Last known good version:  None.
- IDE:  Visual Studio 2022 Community
- Platform Target Frameworks:
  - Android: SDK 30.0 
  - Linux:  OpenSUSE Leap 15.3 via WSL2's Wayland server functionality
  - Windows Classic:  Windows 10 version 2004 (build 19041)
- Target Devices:   Local PC running an Uno Android project via emulator, a local PC running an Uno Skia.Gtk project using WSL, and a local PC running an Uno Skia.Wpf.Host project.

(That is not an exhaustive list, I simply wasn't able to test it on all of the platforms. Because it is a binary break it will happen on any platform except UWP; UWP has always had `public IAsyncAction CoreDispatcher.RunAsync(CoreDispatcherPriority priority, DispatchedHandler handler);` as its signature, so it had no binary compatibility break).
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  Visual Studio 2022 17.0.1 Community running on Windows 11 Pro (10.0.22000 Build 22000) with the most recent Windows Subsystem for Linux version 2 and OpenSUSE 15.3 (note: only needed if you want to test the Skia.Gtk project using WSL; it's not necessary).
</details>

**Reproduction Link**

[SkiaSharpUno4BreakageSample.zip](https://github.com/mono/SkiaSharp/files/7643056/SkiaSharpUno4BreakageSample.zip)

**Comment by nor0x** [comment] 2021-12-02 17:25
i have a related issue with `SKSwapChainPanel` and Uno 4.0 - opened almost at the same time 😂
https://github.com/mono/SkiaSharp/issues/1878

**Comment by robloo** [comment] 2021-12-04 01:58
@jeromelaban This might explain why the PR #1873 builds are failing.

For everyone, also see some comments added to the PR: https://github.com/mono/SkiaSharp/pull/1873#issuecomment-985832737

**Comment by robloo** [comment] 2021-12-04 02:01
> That said, this is probably going to be an ongoing problem for SkiaSharp since if it's compiled against Uno 4 then it will have the same missing method issue (except with the expected and actual signatures reversed) when someone tries to use it with Uno 3.X (or any other version of Uno prior to 4). So you may need to ship two versions, deprecate support for pre-Uno 4, and at some reasonable time in the future cease building new SkiaSharp packages for pre-Uno 4.

I would drop support for all older versions of Uno. If someone is still using old versions of Uno below 4.x they will simply need to use an older version of SkiaSharp. Otherwise, I don't think this is easy to manage going forward.

**Comment by jeromelaban** [comment] 2021-12-04 02:04
#1873 is here to fix the causes for this issue. 

Uno 4.0 introduced (many) binary breaking changes to align with WinUI 3 and avoid discrepancies found when using Uno 3.x and earlier. We're unlikely to break again in the future as Uno is now aligned with WinUI/WinRT and that this API is stable.

**Comment by robloo** [comment] 2021-12-21 17:21
This was fixed with the SkiaSharp 2.88.0-preview.179 nuget (including SkiaSharp.Views and SkiaSharp.Views.Uno)

Any Uno version < 4.0 must use SkiaSharp < 2.88.0-preview.179 and
Any Uno version >= 4.0 must use SkiaSharp >= 2.88.0-preview.179

I believe this issue can be closed unless you want to leave it open until final release (not preview Nugets).

**Closed** 2021-12-21 17:41 UTC
