### ISSUE TITLE
[Bug] SKPath AddArc does not show smooth arc when IsAntialias is true 

### ISSUE THREAD

**Issue by richardvaldiviesomacias** [mono/SkiaSharp#1474] opened 2020-08-21 12:12 UTC
### Description

Using SKPath to draw an arc shows arcs a bit pixeled.

### Steps to Reproduce

1. Create a SKPoint in the center of the screen.
```csharp
        SKPoint center = new SKPoint(Info.Width / 2, Info.Height / 2);
            float radius = (float)Size / 2;
```
2. Create a SKRect 
```csharp
     SKRect dimensions = new SKRect(center.X - radius, center.Y - radius,
                center.X + radius, center.Y + radius);
```
3. Create a SKPaint
```csharp
          var paint = new SKPaint()
            {
                Style = SKPaintStyle.Stroke,
                Color = color, //pick any color
                StrokeWidth = strokeWidth,
                IsAntialias = true,
            };
```
4. Draw the arc
```csharp
    SKPath skPath = new SKPath();
            skPath.AddArc(skRectangle, dimensions.StartAngle, dimensions.SweepAngle);
            canvas.DrawPath(skPath, paint);
```

### Expected Behavior

A smooth arc.

### Actual Behavior

Here is a picture of my circle made using arcs (code attached). If you run the code you would see that the graphic looks chunky in some places

![image](https://user-images.githubusercontent.com/16247065/90888315-a52e9f00-e37b-11ea-9545-868eb2ccffd8.png)
### Basic Information

- Version with issue:
- Last known good version: Latest version of Skia and Xamarin Forms
- IDE: VS 2019
[xamarinsamples.zip](https://github.com/mono/SkiaSharp/files/5108729/xamarinsamples.zip)

**Comment by richardvaldiviesomacias** [comment] 2020-08-27 13:50
After removing IgnorePixelScaling the graphic shows better. Thanks @mattleibow for your advice.

**Comment by mattleibow** [comment] 2020-08-27 14:51
Yeah. 😿  #1177 

The bug in that property is that it ends up scaling up on hi-res screens.

**Comment by mattleibow** [comment] 2020-08-27 14:51
Closing this as a duplicate of #1177

**Closed by mattleibow** 2020-08-27 14:51 UTC
