### ISSUE TITLE
SKCanvasView PaintSurface event never invoked in iOS physical device

### ISSUE THREAD

**Issue by rayita** [mono/SkiaSharp#341] opened 2017-07-15 20:33 UTC
SkiaSharp.Views.Forms  1.59.0, 1.58.1
Xamarin.Froms 2.3.4.247
Xamarin.iOS 10.10

Using a simple SkCanvasView control, everything  works fine in Android and iOS Simulator (any iOS version), but when same application runs in a physical device PaintSurface event is never invoked (neither OnPaintSurface method).

This have been testes in several iPhones and does not work in any of them, but always works in Simulator.

PS: SkGLView doesn't work either.

**Comment by mattleibow** [comment] 2017-07-16 22:16
This is interesting. I just want to check what causes this. Can you check this sample to see if it runs on an iOS device:
https://github.com/mattleibow/SkiaSharpDemo

Also, is there any difference in the code for device/simulator? Can you try a clean/rebuild just to make sure.

Is this Windows or Mac?

Are you able to provide a sample app that doesn't work at all?

**Comment by rayita** [comment] 2017-07-17 12:05
Hello  Mathew, thanks for interest.

I'd tested your SkiaSharpDemo and I got same behavior, works fine in Android and iOS simulator, but not in iOS device, PaintSurface event is never triggered.

There is no diferences between the code for device or simulator, and yes I tried to clean and rebuil many times.

I use to develop in a windows machine with VS 2017, there is, of course, a Mac that compile and deploy to device.

As far as your own sample is doesn't working I think that can be used as example of application that doesn't work.

PS: One more detail, just to clarify, it doesn't work in any case, nor debugging nor deplying app to device as AdHoc or any other methow (is not a debugging envirotment issue).

**Comment by mattleibow** [comment] 2017-07-17 14:07
So, is the sample app a blank screen on the device?
That is really weird. What version of iOS and what device are you using?

**Comment by rayita** [comment] 2017-07-17 14:38
Well not a blank screen, its a correct app with navbar but non of skiasharp object was drawn cause (and i checked it) the PaintSurface was not invoked (screenshot attached).

It's an iPhone 6 with iOS 10.3.2, also tested with 10.3.1 and with a iPhone 7 plus iOS 10.3.2, same result.

![screenshoot](https://user-images.githubusercontent.com/5463765/28273022-74d7d86a-6b0d-11e7-9ca2-91644ea9b595.png)

**Comment by mattleibow** [comment] 2017-07-17 14:45
Incredible! Try this ultra simple app. It should display a red screen with black text.

[TestSkiaSharpApp.zip](https://github.com/mono/SkiaSharp/files/1152966/TestSkiaSharpApp.zip)

**Comment by mattleibow** [comment] 2017-07-17 14:59
Here is a super minimal forms sample that works for me...

[TestSkiaSharpFormsApp.zip](https://github.com/mono/SkiaSharp/files/1153027/TestSkiaSharpFormsApp.zip)

**Comment by rayita** [comment] 2017-07-17 18:41
Same result, blank screen in device (red screen with SkiaSharp text in simulator).
OnPaint method is never called in device.

PS: Just in case I reinstalled Xcode and tried in another device, same result.

**Comment by mattleibow** [comment] 2017-07-17 19:04
Ok, the second shows something... the reason for the black is where the canvas is, and is doesn't resize.

So, for some reason, the ios device is not calling the paint method properly... What version of iOS?

**Comment by mattleibow** [comment] 2017-07-17 19:06
also, what version of xcode? Maybe you can attach the VS help info: "Help" > "About" > "Copy Info" button

**Comment by rayita** [comment] 2017-07-18 08:44
Hello Mathew.

Last test was in  iOS 10.3.2

Xcode version is 8.3.3

That is the info form VS;

> Microsoft Visual Studio Community 2017 
> Version 15.2 (26430.16) Release
> VisualStudio.15.Release/15.2.0+26430.16
> Microsoft .NET Framework
> Version 4.7.02046
> 
> Installed Version: Community
> 
> Visual Basic 2017   00369-60000-00001-AA431
> Microsoft Visual Basic 2017
> 
> Visual C# 2017   00369-60000-00001-AA431
> Microsoft Visual C# 2017
> 
> Common Azure Tools   1.9
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> JetBrains ReSharper Ultimate 2017.1.3    Build 108.0.20170613.154143
> JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.
> 
> Merq   1.1.17-rc (cba4571)
> Command Bus, Event Stream and Async Manager for Visual Studio extensions.
> 
> Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
> Support for debugging Mono processes with Visual Studio.
> 
> NuGet Package Manager   4.2.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Xamarin   4.5.0.486 (fec6f88)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android SDK   7.3.1.2 (9dbc4c5)
> Xamarin.Android Reference Assemblies and MSBuild support.
> 
> Xamarin.iOS and Xamarin.Mac SDK   10.10.0.37 (ad35de4)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

About the linker, I tested your samples without any modification in debug mode so have been tested with out linking. 
My aplications presents no diferences in debug with out linking or in release with sks only linking.


Thanks.

**Comment by rayita** [comment] 2017-07-18 09:56
Hello again Mathew.

Attached the TestSkiaSharpApp detailed build log.

[TestSkiaSharpApp.log.txt](https://github.com/mono/SkiaSharp/files/1155432/TestSkiaSharpApp.log.txt)

**Comment by rayita** [comment] 2017-07-25 17:12
Hello Mathew.

Have been the log helpful?

All my tries have been unsusscesfull, i'm unable to make it work in a iPhone :(

**Comment by rayita** [comment] 2017-08-18 11:17
Finally i found the source of the proble (but not the solution).

In a physical device SkiaSharp.Views.iOS.Extensions.IsValidEnvironment is always false, and this is caused by this error "System.DllNotFoundException: @rpath/libSkiaSharp.framework/libSkiaSharp" when propertie it's initilized.

I search in forums and found some other people with similar problems but in other circustances.

I tried some of the solutions in this post but none works,  until now I got no solution for this problem.

**Comment by mattleibow** [comment] 2017-08-29 20:46
@rayita I looked at your log and tried a few more things, but still can't reproduce this at all. It always works for me. Every time.

The log also indicates that the native library IS being copied just fine:

```
1>Added Item(s): 
1>    _CodesignAppBundleInputs=
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\Entitlements.plist
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\Frameworks\libSkiaSharp.framework\libSkiaSharp
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\Info.plist
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\LaunchScreen.nib
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\Main.storyboardc\BYZ-38-t0r-view-8bC-Xf-vdC.nib
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\Main.storyboardc\Info.plist
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\Main.storyboardc\UIViewController-BYZ-38-t0r.nib
1>        bin\iPhone\Debug\TestSkiaSharpApp.app\TestSkiaSharpApp
```

Have you tried running this on the mac directly (and not via the build agent). I tried VS on Windows and it works fine.

**Comment by rayita** [comment] 2017-09-01 10:28
Hello Mathew.

Finally I found out the problem and the solution.

Yes I also tried directly on the mac and also failed (I tried with VS and Xamarin Studio).
I also checked the build log and the ipa file and the framework was fine in both of them.
So I made one more test and built the app in a different Mac, and in this new Mac all was fine, so my Mac was the problem (and I can't imagine what was the real problem because I even reinstalled all the development tools).

So finally I formatted and reinstalled the whole Mac OS X, XCode and VS, and now all works fine.

Definitely that was a nice poltergeist.

Thanks for your help.

**Comment by mattleibow** [comment] 2017-09-01 16:26
Whaaat... That is super weird!
If it ever happens again let me know. If anyone else has suggestions...

I will close this as it appears to be "fixed" now :)

**Closed by mattleibow** 2017-09-01 16:26 UTC

**Comment by twinharbor** [comment] 2019-11-20 18:30
I'm running into this exact issue now, just rolled out a new version of my app only to find that it doesn't work on physical devices. If anyone has any more insight onto a solution for this, please let me know! Thanks!

**Comment by mattleibow** [comment] 2019-11-20 20:35
@twinharbor could you open a new issue and fill in the template with all the specs. You can also link to this issue for context if you are seeing the same thing.

**Comment by Christoph293** [comment] 2020-03-06 14:48
I had the same issue as @rayita . The emulator works and `OnPaintSurface()` is called on initialization and after every call of `InvalidateSurface()` . As soon as i deploy the application to my iPhone `OnPaintSurface()` is never called. It seems that there is no event fired.
I think there is a bug somewhere so this issue should not be closed even if this appears just sometimes.

I uninstall XCode and VS now as @rayita  said. Hopefully it works.

**Comment by mattleibow** [comment] 2020-03-15 20:54
@Christoph293 could it be this issue: #1129 ?
