### ISSUE TITLE
[QUESTION] I used skiasharp version 1.68.0. But the quality of the generated PDF document is 7882kb. This is too large for saving. Is there a way to reduce the quality?

### ISSUE THREAD

**Issue by mpg-kairyu-ka** [mono/SkiaSharp#1149] opened 2020-02-20 06:00 UTC
You can ask questions here, but there might be better places to do that as well:

 - If you have questions on how to use SkiaSharp with .NET, this is the best place.
 - If you have questions on how to draw a picture, but need some suggestions, there is the community to help:
    - StackOverflow: https://stackoverflow.com/questions/tagged/skiasharp
    - Xamarin Forums: https://forums.xamarin.com
    - Gitter.im Chat: https://gitter.im/xamarin/XamarinComponents
 - If you have questions on skia, or need to ask more advanced questions about the native API, the skia Group is the place to go: https://groups.google.com/forum/#!forum/skia-discuss

But... If you still aren't sure about where to ask your question, then go ahead and ask here! We will try and answer you, but if we can't, then we will help you get the answers you want.

**Comment by mattleibow** [comment] 2020-02-21 11:16
Could you attach some sample code that is causing the PDF to be large? Or is even a blank PDF large for you?

What is the platform/OS and what are you putting on the PDF. A simple snippet of code that is causing the PDF to be large will help a lot.

**Comment by mpg-kairyu-ka** [comment] 2020-02-25 03:43
Thank you for your reply.
Just the simplest text document. Documents similar to salary details. If there is no content, it is about 4kb. However, even if you draw a point, it will become about 7882kb. Very distressed!
The current framework does not support other advanced software! .net core 1.1

**Comment by mattleibow** [comment] 2020-06-10 23:42
Closing this as a duplicate of #848

**Closed by mattleibow** 2020-06-10 23:42 UTC
