### ISSUE TITLE
[QUESTION] Is it possible to user SKGLView in MAUI on Windows and Mac? (and if not, are there any plans for it?)

### ISSUE THREAD

**Issue by marcojak** [mono/SkiaSharp#2403] opened 2023-03-04 22:02 UTC
I'm creating an app with MAUI targeting all platforms but mainly Windows and Mac.
So far I've used SKCanvasView with good results but I would like to use SKGLView for better performances.

I've tried to use it but the app crashes with this message:
Handler not found for view SkiaSharp.Views.Maui.Controls.SKGLView.

I've installed the package SkiaSharp.Views.Maui.Controls.Compatibility hoping to use the previous renderers but without success.

Am I missing something or it's not possible to use SKGLView with MAUI? If so, are there any plans for it?

Thank you very much.

**Comment by renatosc** [comment] 2023-03-19 01:57
Same issue here.

**Comment by TommiGustafsson-HMP** [comment] 2023-04-08 07:40
IIRC, the problem is that OpenGL is not supported on MacCatalyst and that's why you can't use SKGLView for rendering on Mac. You should use Metal, i.e. SKMetalView, but that's not cross-platform. So, AFAIK, at the moment there is no cross-platform solution for GPU acceleration with SkiaSharp + MAUI.

**Comment by marcojak** [comment] 2023-04-08 10:04
Thanks for that.

What about Windows? If I remember correctly, there was a correct
implementation of SKGLView acceleration in skiasharp. Not sure why that
solution cannot be implemented in MAUI.
It seems that this project is almost abandoned...I don't think there are
too many maintainers unfortunately.


Best Regards,
Marco

**Comment by TommiGustafsson-HMP** [comment] 2023-04-08 10:17
Yes, it's weird that they have almost nobody working on this project even though it is so widely used.

**Comment by pauldendulk** [comment] 2023-06-10 07:08
I would be interested in an update on this.

**Comment by mattleibow** [comment] 2023-09-06 14:34
Duplicate of #2050

**Closed** 2023-09-06 14:35 UTC
