### ISSUE TITLE
[FEATURE] Publish SkiaSharp package specifically for use in (ASP).NET Core

### ISSUE THREAD

**Issue by ryanelian** [mono/SkiaSharp#1241] opened 2020-04-18 16:31 UTC
**Is your feature request related to a problem? Please describe.**

SkiaSharp package size is MASSIVE. 

At 88MB + 3MB Linux native package, it's quite taxing on developer machine and build system (CI/CD), often times causing build times to be delayed due to the package download size AND eating build time quota (e.g. GitHub Actions minutes per month).

Also, the final app publish size will also be larger by default, (unless the developer uses self-contained build with explicit Runtime ID) which is not ideal:

![image](https://user-images.githubusercontent.com/8892187/79643305-94eb9500-81cc-11ea-822b-f37d45540f5a.png)

> Example above: Tizen folders contains only SkiaSharp native assets!

**Describe the solution you'd like**

I wish there is another SkiaSharp package by the Mono / SkiaSharp / Microsoft team for use specifically in ASP.NET Core. (e.g. `SkiaSharp.AspNetCore`)

This new package should just consist of these native assets:
- win-x64
- win-x86 (optional)
- linux-x64 (from https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux)
- osx

And the package should just target .NET Standard for optimal package size. (No .NET Framework and other junks, since the unified .NET 5 is coming up anyway. In the future change the target to .NET 5)

I did a rough estimate of the .nupkg size with only those runtime IDs and only .NET Standard. It should come out at only 12MB total ❗ ❗ ❗ 

This new package should play nicely with .NET Core Runtime Deps for Docker: https://hub.docker.com/_/microsoft-dotnet-core-runtime-deps/ or ASP.NET Core for Docker: https://hub.docker.com/_/microsoft-dotnet-core-aspnet/ images for building general web apps and microservices.

It'll also be nice if this happens, as there will be a image processing library "blessed" for use in ASP.NET Core apps.

**Describe alternatives you've considered**

Magick.NET offers such package at 21 MB size https://www.nuget.org/packages/Magick.NET-Q8-x64/ or 46 MB size https://www.nuget.org/packages/Magick.NET-Q8-AnyCPU/

**Additional context**

Related issue https://github.com/mono/SkiaSharp/issues/453

**Comment by Gillibald** [comment] 2020-04-18 16:56
Even better. Make native assets an extra package like the Linux version. Problem solved.

**Comment by mattleibow** [comment] 2020-04-18 18:01
> Make native assets an extra package like the Linux version. Problem solved.

That is the plan.

**Comment by mattleibow** [comment] 2020-04-18 18:04
The future with net5 will only have a single assembly and we will do something about the multiple native assets.

For now, yeah, we could split the packages. Can you not just publish for a specific runtime? You already know where you are going to be running, so no need to have it all. Or are you not creating the docker image?

**Comment by ryanelian** [comment] 2020-04-18 18:26
`Can you not just publish for a specific runtime?`

That is what is happening today.

But this thread is about "tomorrow". I would like to be able to `dotnet publish -c Release` when SkiaSharp is installed into the project AND not worry about the whole app publish size. (e.g. Hand over that folder to customer and say "run this using `dotnet` in Linux or Windows or Mac OS up to you")

Let's just say that we want to optimize publish size for newbies who are not familiar / care with runtime identifiers.

**Comment by mattleibow** [comment] 2020-06-27 22:25
Closing this as a duplicate of #1301

Even though this issue was first, it was around the idea of ASP.NET. Some changes were made to no longer embed the native files inside the assemblies (#1296) but this actually made this issue worse unfortunately. However, the actual work was done so we can either move files around or into separate packages.

I am not sure exactly why the process will be, but I hope to do some cleanup in v2.80.1.

**Closed by mattleibow** 2020-06-27 22:25 UTC
