### ISSUE TITLE
SKMatrix.Concat Ambiguity in VB.Net

### ISSUE THREAD

**Issue by gktval** [mono/SkiaSharp#1076] opened 2019-12-20 19:17 UTC
The SkMatrix.Concat method has two options: with and without 'ref' values. Unfortunately, I am forced into using VB.Net, which cannot specify which Concat method to use except through reflection. Thus, in VB.Net, I will get a compile error "'Concat' is ambiguous because multiple kinds of members with this name exist in structure 'SKMatrix'."  Could I kindly ask that two methods be named slightly different to make it more friendly with other languages such as VB.Net? For instance, maybe:

      public static void Concat(ref SKMatrix target, SKMatrix first, SKMatrix second);

and

      public static void ConcatRef(ref SKMatrix target, ref SKMatrix first, ref SKMatrix second);

Or add a wrapper for VB.Net that calls one of those methods with a different name (This would extend the API without breaking any current functionality). And also make you aware of problems such as this for future design.
Thanks

**Comment by mattleibow** [comment] 2019-12-21 03:03
This is a duplicate of #399

**Closed** 2019-12-21 03:03 UTC
Labels: type-duplicate
