### ISSUE TITLE
[QUESTION] Unable to load shared library 'libSkiaSharp' or one of its dependencies.

### ISSUE THREAD

**Issue by 14skywalker** [mono/SkiaSharp#1999] opened 2022-04-14 08:20 UTC
Deploying my dot.net 5 app with skiasharp with docker on linux, with this in my docker file:

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS final

...

RUN apk add --no-cache icu-libs fontconfig curl
```

Build on thuesday (April 12, 2022) works fine. Build next day causes container to build and run but with runtime error:
```
The type initializer for 'SkiaSharp.SKData' threw an exception. Unable to load shared library 'libSkiaSharp'
or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment
variable: Error loading shared library liblibSkiaSharp: No such file or directory 
```
I can only assume that my `apk add` is now installing new versions.

- Anyone else having this issue?
- Anyone already found the cause?
- What bould be a future proof way of installing the correct libraries?

Thanks!

Before arriving at above conclusion I used these references settings, none of them worked:
```
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.1" />
```
```
    <PackageReference Include="SkiaSharp" Version="2.80.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.2" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.2" />
```
```
    <PackageReference Include="SkiaSharp" Version="2.80.3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.80.3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.3" />
```

**Comment by 14skywalker** [comment] 2022-04-14 09:20
It looks like a change in`FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS final` is the culprit. It was last updated April 12: [docker hub](https://hub.docker.com/_/microsoft-dotnet-aspnet/)

**Comment by Trapov** [comment] 2022-05-17 15:32
hit the same issue today with aspnet:6 tho

**Comment by mattleibow** [comment] 2022-05-17 16:23
And if you do `readelf -d libSkiaSharp.so` on the libSkiaSharp.so, what dependencies is it missing?

**Comment by Trapov** [comment] 2022-05-17 19:59
Strange but it doesn't have the linux variant @mattleibow 

<img width="436" alt="image" src="https://user-images.githubusercontent.com/13402883/168899414-756cb28f-8fd1-4590-83a9-c038e118bf59.png">

**Comment by mattleibow** [comment] 2022-05-17 20:59
oh? That is very interesting. It is in the package:

![image](https://user-images.githubusercontent.com/1096616/168908944-345efadd-5cfb-43ed-80b2-a38517ccae02.png)

Do you not have some code somewhere that might exclude this?

Can you get a binlog of the build? That might show some more info as to why it left the building.

**Comment by Trapov** [comment] 2022-05-18 05:21
Nevermind I had a condition when referencing the package and this condition was wrong so I ended up with no package for linux.

**Comment by Trapov** [comment] 2022-05-18 08:10
We good, it works, thanks for the help anyway :)

**Comment by zxh126** [comment] 2022-08-08 01:20
Add Package SkiaSharp.NativeAssets.Linux or SkiaSharp.NativeAssets.Linux.NoDependencies.

**Comment by mattleibow** [comment] 2022-08-12 19:35
I think the key here is the "or" because installing both packages results in 2 native binaries - and the build selects a random one and you get lucky.

Otherwise, for most general distros/flavors of linux, the packages should be working fine. Usually the OS installs the fontconfig files, but you can confirm by running:

```
readelf -d libSkiaSharp.so
```

If you have fontconfig or don't mind installing/depending on it, you can use the `SkiaSharp.NativeAssets.Linux` package.

If you don't have/want to install fontconfig, you need to use the `SkiaSharp.NativeAssets.Linux.NoDependencies` package instead.

I am closing this issue as I believe the issue is resolved. However, if this is still happening on linux, please open a new issue with specific details of the version of SkiaSharp, the version and distro of the linux used and any other dotnet and sdk versions related.

**Closed by mattleibow** 2022-08-12 19:35 UTC
