### ISSUE TITLE
SkiaSharp in Blazor client side application we are facing libSkiaSharp assembly not found

### ISSUE THREAD

**Issue by MohanaselvamJ** [mono/SkiaSharp#2287] opened 2022-10-17 14:11 UTC
**Description :** 
We are using SkiaSharp to measure a string in ASP.NET Core Blazor application. In Blazor server side application, SkiaSharp works fine without any issue. But, when we use SkiaSharp in Blazor client side application we are facing libSkiaSharp assembly not found issue.

**Code :** 
```
@page "/DocIO"
@inject Microsoft.JSInterop.IJSRuntime JS
@using System.IO
@using SkiaSharp


<p>Click the button to run the code</p>
<button class="btn btn-primary" @onclick="@Create">Create</button>

@code {
    @functions {

        async void Create()
        {
            float skiaMeasurement = 0;
            SKFontStyleWeight weight = SKFontStyleWeight.Normal;
            SKFontStyleSlant sKFontStyleSlant = SKFontStyleSlant.Upright;
            SKFontStyleWidth sKFontStyleWidth = SKFontStyleWidth.Normal;
            try
            {
                using (SKPaint paint = new SKPaint())
                {
                    paint.Typeface = SKTypeface.FromFamilyName("Arial", weight, sKFontStyleWidth, sKFontStyleSlant);
                    paint.Color = SKColors.Black;
                    paint.IsAntialias = true;
                    paint.TextSize = 11;
                    paint.SubpixelText = true;
                    paint.TextAlign = SKTextAlign.Left;
                    paint.TextEncoding = SKTextEncoding.Utf8;
                    string text = "Text";
                    SKRect rect = new SKRect();
                    skiaMeasurement = paint.MeasureText(text, ref rect);
                }
            }
            catch(Exception ex)
            {
                string msg = ex.ToString();
            }

        }
    }
}
```

**Expected Behavior :** 
SkiaSharp should work properly in Blazor client side application.
**Actual Behavior :** 
The following exception is thrown.
_'System.DllNotFoundException: libSkiaSharp assembly:<unknown assembly> type:<unknown type> member:(null)\n  at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_compatpaint_new()\n  at SkiaSharp.SKPaint..ctor () [0x00000] in D:\\a\\1\\s\\binding\\Binding\\SKPaint.cs:25 \n  at Client_side_application.Pages.DocIO.CreateWord () [0x0002d] in D:\\Blazor\\Client-side-application\\Pages\\DocIO.razor:21 '_

**Basic Information :** 
SkiSharp Version with issue : 2.88.3
IDE : Visual Studio 2019

**Reproduction steps:** 
Run the above code example

**Comment by mattleibow** [comment] 2022-10-17 15:15
Duplicate of #2109

**Closed by mattleibow** 2022-10-17 15:15 UTC
