### ISSUE TITLE
UWP app using SkiaSharp 1.60.1 failing in Windows App Certification process

### ISSUE THREAD

**Issue by kareemsulthan07** [mono/SkiaSharp#566] opened 2018-06-24 12:06 UTC
### Description

I have a UWP app, which was for the first version of it deployed, accepted and published in Windows Store. Later added new features to it and now trying to upload a package as an update to it. Since its first version i'm using SkiaSharp. Now, after a while I updated all the packages that it uses to their latest version, including SkiaSharp. After the app package creation the app failing in Windows App Certification due to libSkiaSharp.dll.

Here is the message,

Supported APIs
Error Found: The supported APIs test detected the following errors:

API _CxxThrowException in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __CxxFrameHandler3 in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __intrinsic_setjmp in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __std_exception_copy in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __std_exception_destroy in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __std_type_info_compare in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API longjmp in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API strchr in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API strrchr in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API strstr in vcruntime140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??0?$basic_ios@DU?$char_traits@D@std@@@std@@IEAA@XZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??0?$basic_iostream@DU?$char_traits@D@std@@@std@@QEAA@PEAV?$basic_streambuf@DU?$char_traits@D@std@@@1@@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??1?$basic_iostream@DU?$char_traits@D@std@@@std@@UEAA@XZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??5?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@AEAN@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@_J@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@_K@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?_BADOFF@std@@3_JB in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?_Lock@?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAAXXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?_Unlock@?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAAXXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?_Xbad_function_call@std@@YAXXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?_Xlength_error@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?classic@locale@std@@SAAEBV12@XZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?imbue@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAA?AVlocale@2@AEBV32@@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?imbue@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAXAEBVlocale@2@@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?setbuf@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAPEAV12@PEAD_J@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?showmanyc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?sync@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAHXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?uflow@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAHXZ in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?xsgetn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEAD_J@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API ?xsputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEBD_J@Z in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API _Query_perf_counter in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API _Query_perf_frequency in msvcp140.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. libSkiaSharp.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. libSkiaSharp.dll calls this API.

Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.

### Actual Behavior

One of its previous versions succeeded in the Windows App Cert process also published on Windows Store

### Basic Information

- Version with issue: 1.60.1
- Last known good version:  earlier than 1.60.1 (not sure) 
- IDE:  Visual Studio Community 15.7.4
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:  UWP
  - watchOS:  
  - Windows Classic:  
- Target Devices:
  -   

### Screenshots

![skiasharp_failed](https://user-images.githubusercontent.com/10881118/41818903-0f7615d8-77d5-11e8-98b0-c3a833ab7d02.png)

**Comment by Spielzeug** [comment] 2018-06-25 10:22
We are too experiencing this issue, I could upload the test results, for now just a screenshot.
![2018-06-25 12_22_06-windows app certification kit testergebnisse](https://user-images.githubusercontent.com/3616896/41845052-6d51c9fc-7872-11e8-829e-a106443d95a8.png)

**Comment by mattleibow** [comment] 2018-06-25 10:33
Thanks for reporting this, I fixed this in master and I will get v1.60.2 with the fix out this week.

Duplicate of #536

**Closed by mattleibow** 2018-06-25 10:33 UTC
Labels: area-Build, area-libHarfBuzzSharp.native, area-libSkiaSharp.native, duplicate

**Comment by charlesroddie** [comment] 2018-06-28 12:49
@mattleibow Is 1.60.2 still on track for today or tommorrow? Thanks

**Comment by mattleibow** [comment] 2018-06-28 20:12
@kareemsulthan07 @Spielzeug @charlesroddie I have just pushed out the release and should be available on NuGet. Here are the release notes and all the links: https://github.com/mono/SkiaSharp/releases/tag/v1.60.2
