### ISSUE TITLE
SKPathEffect.CreateDash returns null for odd number of elements in intervals array

### ISSUE THREAD

**Issue by codedevote** [mono/SkiaSharp#168] opened 2016-10-23 17:31 UTC
Used version: 1.54.0

Wasn't able to reproduce v1.54.1, since samples didn't compile on my box.

Repro:
Change (this line)[https://github.com/mono/SkiaSharp/blob/v1.54.0/samples/SharedDemo/SkiaSharp.Demos.cs#L1002] and make the intervals[] array have an odd number of elements, like 

`using (var effect = SKPathEffect.CreateDash (new [] { 15f, 5f, 5f }, 0)) `

In the above line `effect `will be null.

**Comment by tdenniston** [comment] 2016-10-24 12:50
I'll let the SkiaSharp owners correct me if I'm wrong, but I believe that's working as intended. If you look at [the native Skia docs for dashing](https://github.com/mono/skia/blob/a01855170d8957a7b6fec253f8e56bcf5ae7d818/include/effects/SkDashPathEffect.h#L39) it specifies that the intervals array should contain an even number of elements.

The intervals array should contain a list of pairs of `StrokeDist, GapDist`. Therefore a simple method to fix your problem is to concatenate a copy of your intervals array onto itself (i.e. `15, 5, 5, 15, 5, 5`). That's the method followed e.g. by the [SVG standard](https://www.w3.org/TR/SVG11/painting.html#StrokeDasharrayProperty)

**Comment by codedevote** [comment] 2016-10-24 13:26
Thanks for the clarification. Nevertheless, a factory method returning null without any hints on what was wrong seems still confusing. 

In my opinion, it should either throw an ArgumentException or, if the second approach you suggest creates the intended dash effect, it could be an option to silently apply that modification within the factory method. Whatever seems the solution that's better aligned with the design of the skia sharp library I would be happy to send a PR containing the desired fix.

**Comment by tdenniston** [comment] 2016-10-24 13:29
Agreed, the docs should specify that. I know @mattleibow has a done bunch of docs improvements that will be released with the next version, so perhaps that work is already done.

**Comment by mattleibow** [comment] 2016-10-24 13:58
@tdenniston Thanks for commenting. You are correct, it is working as intended. And, I have added some docs.

@codedevote @tdenniston About the exception... We are in the fortunate position to make decisions. I think C++ returns null as that is preferable to exceptions there. I also am creating a dumb API wrapper - acts as C++ acts. However, since we are doing a .NET API, maybe throwing an arguments exception is actually better. For example, I do throw a few null exceptions in some places - even though nullrefex is a bit different. I am seriously considering adding an exception for hard rules - so there will be no need to hit the docs or do any research.

An example of a hard rule would be the fact that "a color table is exactly 256 items", a "dash must be even number", the "stream cannot be null".

Any thoughts on whether an exception is a good thing, or should we just leave it up the docs?

**Comment by codedevote** [comment] 2016-10-24 14:29
I'll throw in one more option of approaching hard rules:

Instead of e.g. using an integer[] for the dash/gap definition, introduce a proper type, that just makes the invalid states unrepresentable. E.g. having a type like this

`class DashDefinition {
  public float Dash {get; set; }
  public float Gap {get; set; }
}`

would allow for a DashDefinition[] to be passed to the factory method, actually enforcing an even number of dash/gap.

As far as I am concerned, I would either use explicit types (preferred) or throw an ArgumentException for hard rules (as I think this is more idiomatic C# than returning null).

**Comment by tdenniston** [comment] 2016-10-24 14:36
The type-enforced approach would seem like the best approach except for the fact that SkiaSharp is (nominally) a thin wrapper around Skia. If there are small differences like `DashDefinition[]` instead of `float[]`, SkiaSharp users might start to wonder what other subtle differences there are that they are missing. They also might wonder whether a function that takes `DashDefinition[]` has the same functionality as the native Skia method, even if it has the same name.

So I guess if we're voting here, I'd vote for the ArgumentException approach. That seems like a nice middle ground, and as @codedevote noted, probably more idiomatic in C#.

**Comment by mattleibow** [comment] 2016-10-24 20:35
Thanks for the info. I am using an exception so that I don't stray too far off the underlying skia. They may cause issues if the decide to change thing from underneath us (again). I now throw an exception for various cases and the messages should be helpful

**Closed by mattleibow** 2016-10-24 20:35 UTC
Labels: help wanted, NEEDINFO
