### ISSUE TITLE
[BUG] Crash on SkBitmap(x,y) constructor on Android when upgrading SkiaSharp.Views.Forms from 1.68.3 to 2.80.0

### ISSUE THREAD

**Issue by mscherotter** [mono/SkiaSharp#1395] opened 2020-07-11 01:54 UTC
**Description**

Code that worked now crashes when upgrading to SkiaSharp.Views.Forms to 2.80.0

**Code**

  var bitmap = new SKBitmap(114, 108);

**Expected Behavior**

not crash 

Exception Details:
System.DllNotFoundException
  Message=libSkiaSharp.so assembly:<unknown assembly> type:<unknown type> member:(null)

07-10 18:44:08.502 D/Mono    ( 5070): DllImport error loading library 'libSkiaSharp.so': 'dlopen failed: library "libSkiaSharp.so" not found'.
07-10 18:44:08.502 W/Mono    ( 5070): DllImport unable to load library 'libSkiaSharp.so'.
**System.DllNotFoundException:** 'libSkiaSharp.so assembly:<unknown assembly> type:<unknown type> member:(null)'

Upgrading to the latest SkiaSharp.Views.Forms 

- Version with issue:  2.8.0
- Last known good version:  1.68.3
- IDE:  Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 10.0 
- Target Devices:   
  - Surface Duo Emulator 

**Screenshots**

**Reproduction Link**

**Comment by mattleibow** [comment] 2020-07-11 04:12
Ah, this might be because you may have not yet installed the SkiaSharp package into the Android app project?

Might be like #1393

**Comment by mscherotter** [comment] 2020-07-11 15:48
That was it.  Thanks for the prompt and accurate response!

**Comment by mattleibow** [comment] 2020-07-11 20:24
AWESOME! Thanks for upgrading and letting me know. Confirmation that I need to think of the fix for #1393 because the dependencies are not propagating as expected. Open any new issues if you find something that has changed or not working as expected. Closing this now.

**Comment by mattleibow** [comment] 2020-07-31 11:31
Closing this as a duplicate of #1393

**Closed** 2020-07-31 11:31 UTC
