### ISSUE TITLE
[BUG] Shadders with SkiaSharp.Views.WPF Dont Work

### ISSUE THREAD

**Issue by Kuumba123** [mono/SkiaSharp#2536] opened 2023-07-26 11:25 UTC
**Description**

Calling a Drawing function while  using an SKPAINT brings up an System.Runtime.InteropServices.SEHException and  of course ends the program. My code is based off an example I found someone in this repro (Im not super used to graphics API but I really need shadders for my next project and WPF's shadders are really hard to work when it comes to my low level projects) . Also I am using SkiaSharp.Views.WPF so that I can easlily use SkiSharp with WPF . That might be related to the problem but there wasn't much xaml code to begin with

**Code**
```cs
        private void AUView_PaintSurface(object sender, SkiaSharp.Views.Desktop.SKPaintSurfaceEventArgs e)
        {
            //SkiaSharp.SKRuntimeEffect
            // Your SkiaSharp drawing code here
            using (SKCanvas canvas = e.Surface.Canvas)
            {

                // input values
                float threshold = 1.05f;
                float exponent = 1.5f;

                // image source
                 var blueShirt = SKImage.FromEncodedData(@"D:\Images\PogYouMan\PogYouMan.png");
                 var textureShader = blueShirt.ToShader();

                // shader
                var src = @"
uniform shader color_map;
uniform float scale;
uniform half exp;
uniform float3 in_colors0;
half4 main(float2 p) {
    half4 texColor = sample(color_map, p);
    if (length(abs(in_colors0 - pow(texColor.rgb, half3(exp)))) < scale)
        discard;
    return texColor;
}";
                var effect = SKRuntimeEffect.Create(src, out var errorText);

                // input values
                var uniforms = new SKRuntimeEffectUniforms(effect)
                {
                    ["scale"] = threshold,
                    ["exp"] = exponent,
                    ["in_colors0"] = new[] { 1f, 1f, 1f },
                };

                // shader values
                var children = new SKRuntimeEffectChildren(effect)
                {
                    ["color_map"] = textureShader
                };

                // create actual shader
                var shader = effect.ToShader(true, uniforms, children);

                // draw as normal
                canvas.Clear(SKColors.Black);
                var paint = new SKPaint { Shader = shader };
                canvas.DrawRect(SKRect.Create(400, 400), paint);
            }
        }
```
**XAML**
```xaml
    <Window x:Class="SkiSharpTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:skia="clr-namespace:SkiaSharp.Views.WPF;assembly=SkiaSharp.Views.WPF"
        xmlns:local="clr-namespace:SkiSharpTest"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <skia:SKElement  Width="100" Height="100" Name="AUView" PaintSurface="AUView_PaintSurface"/>
    </Grid>
</Window>
```

(I get the exception on the canvas.DrawRect line)
**Expected Behavior**

**Actual Behavior**

?
**Basic Information**

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 
  Windows 10
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by mattleibow** [comment] 2023-07-31 16:32
As of today, `SKRuntimeEffect` is not supported on a raster/bitmap canvas and only on the GPU.

**Comment by mattleibow** [comment] 2023-07-31 16:32
Duplicate of https://github.com/mono/SkiaSharp/issues/1822

**Closed** 2023-07-31 16:35 UTC

**Comment by Kuumba123** [comment] 2023-08-01 00:49
thanks for letting me know ! Does the custom shadders work with WinForm hosted inside WPF ?
