### ISSUE TITLE
Can't draw text using default typeface on Linux

### ISSUE THREAD

**Issue by Ziriax** [mono/SkiaSharp#1131] opened 2020-02-07 13:25 UTC
**Description**

Can't draw text using `SKTypeface.Default` under WSL (Debian) or Docker, .NET Core 3.1, host Windows 10 Pro x64 1903.

Packages used are `SkiaSharp` and `SkiaSharp.NativeAssets.Linux.NoDependencies`, 1.68.2-preview.29 or older versions.

Explicitly loading a typeface fixes the problem.

**Code**

```CS
	using var surface = SKSurface.Create(new SKImageInfo(256, 256));
	using var canvas = surface.Canvas;
	canvas.Clear(SKColors.SkyBlue);

	using var paint = new SKPaint
	{
		Color = SKColors.Yellow, 
		TextAlign = SKTextAlign.Center, 
		TextSize = 64,
		Typeface = SKTypeface.Default
	};

	canvas.DrawText("foobar", 128, 128, paint);

	using var image = surface.Snapshot();
	image.SaveAs("test.png", SKPngEncoderOptions.Default);
```

**Expected Behavior**

The output should contain the text "foobar" on a skyblue background.

**Actual Behavior**

The output doesn't contain any text, but the background is skyblue, so rendering did take place.

**Basic Information**

- Version with issue:  1.68.2 preview
- Last known good version:  Can't find any version that works.
- IDE:  Visual Studio 2019 Enterprise
- Platform Target Frameworks: 
  - Linux:  WSL/Debian/10.2 or Docker mcr.microsoft.com/dotnet/core/sdk:3.1-buster

**Reproduction Link**

This [commit](https://github.com/Ziriax/SkiaBugs/commit/d1779e809acbe5a478213fb4053cfd9cefc6f751) shows the problem

This [commit](https://github.com/Ziriax/SkiaBugs/commit/1f47b9835b03a68aa0cda489cc73add5ce89279e) shows that loading a specific typeface solves the problem, but I guess the default typeface should work or at least throw an exception, so I consider this a bug

Maybe using the package `SkiaSharp.NativeAssets.Linux` that requires FontConfig etc also fixes this, but I haven't tested that yet.

**Comment by Gillibald** [comment] 2020-02-07 13:51
`SkiaSharp.NativeAssets.Linux.NoDependencies` isn't supporting a font manager and therefore only fonts loaded by file or stream are working.

**Comment by Ziriax** [comment] 2020-02-07 14:12
Okay, got it. But it would be very useful if at least something is logged, or an exception is thrown?

**Comment by Gillibald** [comment] 2020-02-07 15:07
It should probably called `SkiaSharp.NativeAssets.Linux.NoFontManager` or `SkiaSharp.NativeAssets.Linux.NoFontConfig`

**Comment by Ziriax** [comment] 2020-02-07 15:31
I'm trying to get a better understanding. I'm a veteran Windows developer, so I might make newbie mistakes on Linux ;-)

- `SkiaSharp.NativeAssets.Linux.NoDependencies`: this comes with just a `libskia` native library, with all libraries (libpng etc) linked in statically, without `FontConfig`? It can run on a system that hasn't any of the dependencies installed. Will it pickup `FontConfig` when it is installed optionally?

- `SkiaSharp.NativeAssets.Linux`: this also just comes with a `libskia` native library, but expects all dependencies to be installed on the system? It requires `FontConfig` to run?

**Comment by Gillibald** [comment] 2020-02-07 15:40
`SkiaSharp.NativeAssets.Linux` dynamically links fontconfig and `SkiaSharp.NativeAssets.Linux.NoDependencies` is built without any dependency on fontconfig and therefore has no font manager. It is just left out.

**Comment by mattleibow** [comment] 2020-02-07 15:40
Text _should_ work, because it has the "custom" font manager which loads fonts from the default directory:

`/usr/share/fonts/`

> https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/ports/SkFontMgr_custom_directory_factory.cpp

**Comment by mattleibow** [comment] 2020-02-07 15:42
This _should_ be included: https://github.com/google/skia/blob/chrome/m68/BUILD.gn#L395-L409

But, do you have any fonts installed? Are there any available in WSL?

**Comment by Gillibald** [comment] 2020-02-07 15:42
Okay so it has a font manager but has no default set. So we should try to set one. Probably just look for a common one.

**Comment by mattleibow** [comment] 2020-02-07 15:42
Ah, yeah. Or the first one.

**Comment by Gillibald** [comment] 2020-02-07 18:00
https://github.com/google/skia/blob/master/src/ports/SkFontMgr_custom.cpp#L153

**Comment by mattleibow** [comment] 2020-02-07 20:23
Although there is this line that _should_ pick one: https://github.com/google/skia/blob/master/src/ports/SkFontMgr_custom.cpp#L173

_Just trying to get me Docker and/or WSL working again..._

**Comment by mattleibow** [comment] 2020-02-07 22:16
So I just tested on the `mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim` Docker image, there are no fonts at all. 

So how do we do this? You probably just want to copy your font files to the `/usr/share/fonts/` directory.

This should fix it for you:

```dockerfile
...
COPY --from=publish /app/publish/*.ttf /usr/share/fonts/
COPY --from=publish /app/publish .
...
```


> After battling a bit I looked at the source and realized something. Linux is case-sensitive. Yay. In my tests, I was using the TIMES.TTF file that I copied from Windows.
>
> Yay.

**Comment by Ziriax** [comment] 2020-02-07 22:45
Amazing how quickly you guys got on top of this, thanks for all the info!

Interestingly, all the default fonts are copyrighted and require licensing, unless these expired, not sure... 

Would be nice to include Roboto or some other free Google font as the default...

Because picking the first font would result in a different default one if others are added, that would be strange from a user's point of view IMHO.

Anyway in our case we will never use the default font, I just wanted to report this behaviour, I was expecting an exception, error, or null default typeface.

**Comment by Gillibald** [comment] 2020-02-07 23:10
Returning nullptr for not found typefaces is by design. Not having any font is totally unexpected. But I think for the default we could throw an exception because that means something is wrong with the font manager.

Too bad the font manager is defined at compile time. If we could somehow have a proxy font manager we could make this pluggable. So if one font manager implementation breaks we could have a fallback or even a managed one that is fully customizable. Crippled platforms like Nano Server wouldn't be an issue anymore.

**Comment by mattleibow** [comment] 2020-02-08 18:35
Yeah. Did you open an issue for that at all? I think you asked for this in the past. The font manager is a bit of work as there are a few overrides, but then there are all the supporting classes - such as the custom style set and custom typeface types. And then there is the big font host. This is either the FreeType (linux), DirectWrite (windows), CoreText (mac) and the deprecated GDI. Right now, the custom one only works on Linux as it uses the FreeType and some linux-y things.

**Comment by mattleibow** [comment] 2020-02-08 18:38
I am closing this issue as I believe the original issue is solved, it just needed some fonts, any fonts.

**Closed by mattleibow** 2020-02-08 18:38 UTC
