### ISSUE TITLE
[BUG] SkiaSharp 2.8.0 not packaged properly for Mac?

### ISSUE THREAD

**Issue by btschumy** [mono/SkiaSharp#1443] opened 2020-08-03 16:32 UTC
**Description**

I have recently been trying to use SkiaSharp in my Xamarin Forms app which I'm building on macOS. I have installed the nuget SkiaSharp.Views.Forms (2.80.1), Whenever I call SkiSharp code I get the following during linking phase:

/Users/bill/Projects/OurGalaxyX/OurGalaxyX.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (OurGalaxyX.iOS)
/Users/bill/Projects/OurGalaxyX/OurGalaxyX.iOS/error MT5209: Error: framework not found libSkiaSharp (OurGalaxyX.iOS) Native linking

Removing the code makes the error go away.

I have downloaded some SkiaSharp code that uses 1.68.2-preview.60 and it does compile and run.

If I uninstall 2.80.1 and install 1.68.3 then the library is found and the executable links correctly.

Is there a problem with he 2.XX package on Mac?

**Code**

**Expected Behavior**

The app should link correctly 

**Actual Behavior**

It fails linking with error:
/Users/bill/Projects/OurGalaxyX/OurGalaxyX.iOS/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (OurGalaxyX.iOS)
/Users/bill/Projects/OurGalaxyX/OurGalaxyX.iOS/error MT5209: Error: framework not found libSkiaSharp (OurGalaxyX.iOS) Native linking

**Basic Information**

- Version with issue:  2.80.0
- Last known good version:  1.68.3
- IDE:  Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.0
- Target Devices:   Compiling for iPad

<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

**Comment by mattleibow** [comment] 2020-08-03 23:42
I think this might be #1393... It should be fixed in the latest preview.

A workaround would be to just install the package into the app project as well.

**Comment by mattleibow** [comment] 2020-08-04 13:37
Closing this as a duplicate of #1393

**Closed by mattleibow** 2020-08-04 13:37 UTC
