### ISSUE TITLE
[BUG] .net maui SkiaSharp crashes 

### ISSUE THREAD

**Issue by lerche27** [mono/SkiaSharp#3019] opened 2024-09-26 14:44 UTC
### Description

Skiasharp crashes when the Maui application is created with WindowsSdkPackageVersion 10.0.19041.41.
The application works perfectly with 10.0.19041.34.

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

Windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lerche27** [comment] 2024-09-26 17:46
👎
The problem is caused by the use of WindowsSdkPackageVersion 10.0.19041.41 and not by a missing .UseSkiaSharp().

**Comment by inforithmics** [comment] 2024-09-27 05:13
It is this issue https://github.com/mono/SkiaSharp/issues/2999
It is fixed in the Main Branch but no Skiasharp nuget is Release Yet

**Comment by lerche27** [comment] 2024-09-27 07:36
Thanks for the hint. I really searched for days, but obviously overlooked this entry.
If I see it correctly, the current Maui CommunityToolkit versions require this WindowsSDK version, i.e. without a problem solution it is not possible to switch to current versions.
Question to the great SkiaSharp team: When will there be a bug-fixed version?
Thank you very much for your great work.

**Comment by mattleibow** [comment] 2024-10-25 16:29
Closing this for now as the issue is fixed for both v2 and v3 in the latest preview.

**Closed by mattleibow** 2024-10-25 16:29 UTC
Labels: type/bug
