### ISSUE TITLE
Why bitmap drawing on rotated canvas is slow?

### ISSUE THREAD

**Issue by TabishRafiq** [mono/SkiaSharp#746] opened 2019-01-01 07:39 UTC
I am switching to SKIA SHARP from GDI+ is found SKIA SHARP very fast in everything except when I tried drawing on canvas with rotation. Even images with very low take time when I drag but I can do that easily with GDI even very large images

**Comment by TabishRafiq** [comment] 2019-01-15 16:18
@mattleibow can you please look into it?

**Comment by mattleibow** [comment] 2019-01-24 03:10
Closing this as a duplicate of #758

**Closed by mattleibow** 2019-01-24 03:10 UTC
Labels: question
