### ISSUE TITLE
[BUG] MAUI: SKCanvasView crash, unable to display SKBitmap directly

### ISSUE THREAD

**Issue by koszeggy** [mono/SkiaSharp#2139] opened 2022-07-01 13:55 UTC
**Description**

I try to render an `SKBitmap` on the view directly. In a Xamarin multi target app I could use `SKCanvasView` (from SkiaSharp.Views.Forms) and its `OnPaintSurface` and it worked perfectly.

**Failed attempt 1:**

But when I try the same in a MAUI app (this time `SKCanvasView` is referenced from the SkiaSharp.Views.Maui.Controls package) the application crashes.

```xaml
<skiaCtrls:SKCanvasView x:Name="canvasView" PaintSurface="CanvasView_OnPaintSurface" HeightRequest="100"/>
```
```cs
private SKBitmap bitmap;

private void ButtonClicked(object sender, EventArgs e)
{
    bitmap = GenerateBitmap(); // some very standard premultiplied BGRA8888 bitmap
    canvasView.InvalidateSurface(); // to invoke CanvasView_OnPaintSurface
}

private void CanvasView_OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
{
    if (bitmap == null)
        return;
    SKImageInfo info = e.Info;
    SKSurface surface = e.Surface;
    SKCanvas canvas = surface.Canvas;
    canvas.DrawBitmap(bitmap, info.Rect);
}
```
Whereas this code worked in Xamarin, it crashes with MAUI:
* Windows: `Microsoft.UI.Xaml.Controls.Frame.NavigationFailed` was unhandled.
The `Exception` property of the event argument is a `COMException`: Catastrophic failure (0x8000FFFF (E_UNEXPECTED))
* Android: Microsoft.Maui.Platform.HandlerNotFoundException: 'Handler not found for view SkiaSharp.Views.Maui.Controls.SKCanvasView.'

**Failed attempt 2:**

SkiaSharp.Views.Maui.Controls has an `SKBitmapImageSource` class, which appears to be an elegant solution to expose an `SKBitmap` as a regular `ImageSource`:

```xaml
<Image x:Name="imgTest" HeightRequest="100"  HorizontalOptions="Center"/>
```
```cs
private void ButtonClicked(object sender, EventArgs e) =>
    imgTest.Source = new SKBitmapImageSource { Bitmap = GenerateBitmap() };
```

* Windows: Nothing happens (the bitmap is generated but the image does not appear)
* Android: System.InvalidOperationException: 'Unable to find a image source service for SkiaSharp.Views.Maui.ISKBitmapImageSource.'

**Failed attempt 3:**

I tried to use a `GraphicsView` instead (from the Microsoft.Maui.Controls package):
```xaml
<GraphicsView x:Name="graphicsViewTest" HeightRequest="100"/>
```
```cs
private void ButtonClicked(object sender, EventArgs e)
{
    graphicsViewTest.Drawable = new SkiaImage(GenerateBitmap());
    graphicsViewTest.Invalidate();
}
```
* Windows: Nothing happens (the bitmap is generated but the image does not appear)
* Android: NotSupportedException from SkiaImage.ToPlatformImage

**Failed attempt 4:**

As per Microsoft's [guideline](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/controls/graphicsview) I tried to create a custom `IDrawable` implementation for a `GraphicsView` and use the drawing operations of `ICanvas`:
```xaml
<GraphicsView x:Name="graphicsViewTest" HeightRequest="100"/>
```
```cs
private SKBitmap bitmap;

public MainPage()
{
    InitializeComponent();
    graphicsViewTest.Drawable = new MyDrawable(this);
}

private void ButtonClicked(object sender, EventArgs e)
{
    bitmap = GenerateBitmap();
    graphicsViewTest.Invalidate();
}

private class MyDrawable : IDrawable
{
    private readonly MainPage owner;
    public MyDrawable(MainPage owner) => this.owner = owner;

    public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        if (owner.bitmap == null)
            return;
        canvas.DrawImage(new SkiaImage(owner.bitmap), dirtyRect.X, dirtyRect.Y, dirtyRect.Width, dirtyRect.Height);
    }
}
```
* Windows: Does nothing. Turns out, it's because `canvas.DrawImage` just returns if the passed `IImage` is not a `W2DImage`. (???!!!) Doesn't it violate a lot of design rules?
* Android: Throws `NotSupportedException`. `canvas` is now a `ScalingCanvas`, which wraps a `PlatformCanvas`, which wraps an `Andorid.Graphics.RecordingCanvas`
 
**Expected Behavior**

All of the solutions above seem to be logical to me. Attempt 1 is clearly a bug and should work.

And though attempts 2-4 also seem correct I cannot decide whether they are just not implemented yet or I misunderstood the design choices. Can you please clarify if they should work (maybe later on)?

**Versions**
* SkiaSharp: 2.88
* Windows: Version 10.0.19044.1766
* Android: Android 11.0 API 30 (emulated Pixel 5)
* SkiaSharp.Views.Maui.Controls: 2.88.1-preview.79
* Microsoft.Maui.Graphics.Skia: 6.0.403

**Disclaimer**
* I could not test MacOS and Linux
* I know saving as .png + `PlatformImage.FromStream` would "work" but unfortunately that is an unacceptable solution for me

**Reproduction Link**

See the attachment. It now executes Attempt 1 but you can uncomment the other attempts, too.
[MauiApp1.zip](https://github.com/mono/SkiaSharp/files/9029277/MauiApp1.zip)

**Comment by koszeggy** [comment] 2022-07-02 13:08
Update: I opened a [discussion](https://github.com/dotnet/maui/discussions/8490) in the dotnet/maui repo. Attempts 3 and 4 seem to be at their side but I'm not 100% sure where the boundaries are.

**Comment by cangunaydin** [comment] 2022-07-03 10:48
Hi,
I am also trying to run a simple sample with skiasharp and maui. I am having the same problem that you described in your first attempt on my project. And to make it crash, inserting the skiacanvas object to xaml is enough.
<skia:SKCanvasView x:Name="skiaView" />

So i was wondering, am i doing sth wrong with installation or officially skiasharp doesn't work with maui?

**Comment by timctrahan** [comment] 2022-07-05 21:44
I am having this same sequence of issues myself.  After weeks of coding a graphics library to generate the images I want displayed on my maui page, I have hit a brick wall trying to get this last part to work.  I generate an SkBitmap and get the same crash when trying to use SkCanvasView and when trying to use the Maui Graphics view, I haven't been able to figure out how to render my skbitmap. trying with graphicsview says toplatformimage not supported.  This is very frustrating

**Comment by cangunaydin** [comment] 2022-07-06 11:05
Just an update from me, i have managed to fix the problem after long struggle,
To use SKCanvasView you need to configure this line in mauiprogram.cs in your project. Tell the maui to use skiasharp with this method
**.UseSkiaSharp()**
```
var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .UseSkiaSharp()
```
                
and for drawing bitmap, i believe it depends on what kind of bitmap data you have.
for ex: i had raw **rgba** data so i will be able to draw the bitmap with this code, here i am drawing it from byte array
```
using (var data = SKData.CreateCopy(_frameBuffer))
            using (var original = new SKBitmap())
            {
                // create a new bitmap using the memory
                original.InstallPixels(new SKImageInfo(_frameWidth, _frameHeight, SKColorType.Rgba8888), data.Data);
                using (var resized = original.Resize(new SKImageInfo(canvasWidth, canvasHeight), SKFilterQuality.Medium))
                {
                    canvas.DrawBitmap(resized, 0, 0);
                }
            }
```

here in this issue @mattleibow explained it nicely. https://github.com/mono/SkiaSharp/issues/603

and for the .jpeg file that i have downloaded i can draw the bitmap like this.

```
 using (var image = SKBitmap.Decode(_frameBuffer))
            {
                canvas.DrawBitmap(image, 0, 0);
            }
```
            
some notes that i have found out while i am trying.

- I couldn't use SKGLView it throws an error on maui, probably as a default, skcanvasview use gpu. But i am not sure about this
- second thing is when i try to installpixels in this code
`original.InstallPixels(new SKImageInfo(_frameWidth, _frameHeight, SKColorType.Rgba8888), data.Data); `
if i do not define the type as Rgba8888, it loads the image with different format. Colors are kind of weird since it is a different format. But if i do not give the type in blazor with SKGLView it loads it succesfully, so i was stucked with that for a long time to find out the problem about weird colors.

hope this can help someone.

**Comment by andressbarajas** [comment] 2022-08-04 15:19
6 Letters. SAVIOR ^^^

**Comment by mattleibow** [comment] 2022-08-11 08:51
Duplicate of #2013

The issue is there is no way for SkiaSharp to register handlers dynamically: https://github.com/dotnet/maui/issues/7258

Upvote that issue to get this working magically.

**Closed by mattleibow** 2022-08-11 08:51 UTC
