### ISSUE TITLE
Xamarin 4.0 and SkiaSharp 

### ISSUE THREAD

**Issue by HugoTruffe** [mono/SkiaSharp#854] opened 2019-05-29 15:07 UTC
Hi People.

I am updating my project to Xamarin 4.0, and I am using skiaSharp 1.68.0 but I have this problem.

/Users/LALA/Projects/Clarika/Imperial-ClienteFiel/ClienteFiel.Forms.iOS/MTOUCH: Error MT0009: Error while loading assemblies: /Users/hugo/.nuget/packages/skiasharp/1.68.0/runtimes/win-x86/native/libSkiaSharp.dll (MT0009) (ClienteFiel.Forms.iOS)

My question.

Do support SkiaSharp the new version o Xamarin?

Thx!

**Comment by HugoTruffe** [comment] 2019-05-29 19:31
In Android is running correctly, only in iOS is the bug

**Comment by evelynhull710** [comment] 2019-05-30 23:04
I'm having exactly the same problem

**Comment by mattleibow** [comment] 2019-06-07 14:25
@HugoTruffe @evelynhull710 do you have more information on the versions of the IDE and Xamarin.iOS? You can get this from the IDE's about dialog.

**Comment by mattleibow** [comment] 2019-06-07 14:29
This appears to be a duplicate of https://github.com/mono/SkiaSharp/issues/855

**Closed by mattleibow** 2019-06-07 14:29 UTC
Labels: need-info, question

**Comment by amirvenus** [comment] 2019-06-11 18:08
I am having the same problem. I cannot build Xamarin.Forms.iOS anymore
