### ISSUE TITLE
I do not understand how canvas.DrawBitmap work. I want to cut my image into 9 puzzle. here is my code... there is something wrong

### ISSUE THREAD

**Issue by Urien2017** [mono/SkiaSharp#385] opened 2017-10-24 21:55 UTC
```csharp
        Assembly assembly = GetType().GetTypeInfo().Assembly;
        Stream stream = assembly.GetManifestResourceStream("wallpaper.jpg");
        SKManagedStream skStream = new SKManagedStream(stream);
        SKBitmap skBitmap = SKBitmap.Decode(skStream);

        int coordsX = 3;
        int coordsY = 3;

        int pX = skBitmap.Width / coordsX ;
        int pY = skBitmap.Height / coordsY;

        int count = 1;

        for (int i = 0; i < coordsX; i++)
        {
            for (int j = 0; j < coordsY; j++)
            {
                SKImageInfo info = new SKImageInfo(pX, pY);
                var pieceBitmap = new SKBitmap(info);

                using (var canvas = new SKCanvas(pieceBitmap))
                {
                   canvas.DrawBitmap(skBitmap, i * pX, j * pY);
                }

                SKImage skImg = SKImage.FromBitmap(pieceBitmap);

                SKData skImgData = skImg.Encode(SKEncodedImageFormat.Png, 100);

                IFolder rootFolder = FileSystem.Current.LocalStorage;
                IFolder folder = await rootFolder.CreateFolderAsync("PiecesFolder", CreationCollisionOption.OpenIfExists);
                IFile file = await folder.CreateFileAsync(string.Concat("Piece", count.ToString(),".png"), CreationCollisionOption.ReplaceExisting);

                using (Stream streamSave = await file.OpenAsync(FileAccess.ReadAndWrite))
                {
                    skImgData.SaveTo(streamSave);
                }

                Button btn = this.FindByName<Button>(string.Concat("button", count.ToString()));
                btn.Image = (FileImageSource)ImageSource.FromFile(file.Path);

                count++;
            }
```

**Comment by mattleibow** [comment] 2017-10-26 01:59
What is wrong? What appears?

Having a quick look at your code I notice this: `canvas.DrawBitmap(skBitmap, i * pX, j * pY)` I may be wrong, but won't that only be correct for the first block, the others will all be off the bitmap? Maybe the coordinates should be `canvas.DrawBitmap(skBitmap, i * -pX, j * -pY)` - note the negative.

**Comment by mattleibow** [comment] 2017-10-26 02:01
Maybe this will help: https://developer.xamarin.com/api/member/SkiaSharp.SKCanvas.DrawBitmap/p/SkiaSharp.SKBitmap/System.Single/System.Single/SkiaSharp.SKPaint/

**Comment by migueldeicaza** [comment] 2017-12-03 03:44
closing as it is not a bug report.

**Closed by migueldeicaza** 2017-12-03 03:44 UTC
