### ISSUE TITLE
[BUG] SkiaSharp V2 BreakText only returns integers on Linux

### ISSUE THREAD

**Issue by Gillibald** [mono/SkiaSharp#1390] opened 2020-07-08 16:05 UTC
**Description**

1.68.3 `paint.BreakText("", 150, out measuredWidth);` // measuredWidth: 144.023438

2.80.0 `paint.BreakText("", 150, out measuredWidth);` // measuredWidth: 147

Typface: `Liberation Mono`
TextSize: `12`
Text: https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.RenderTests/Media/FormattedTextImplTests.cs#L32

**Code**

**Expected Behavior**

**Actual Behavior**

**Basic Information**

- Version with issue: 2.80.0 
- Last known good version: 1.68.3 
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux: Ubuntu 16.04.6 LTS  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 

**Screenshots**

**Reproduction Link**

**Comment by Gillibald** [comment] 2020-07-08 16:07
I can get around this issue by using HarfBuzz to do the measures but still, this is somehow unexpected. OSX and Windows produce the expected results.

**Comment by mattleibow** [comment] 2020-07-08 16:28
Let me have a look.

**Comment by mattleibow** [comment] 2020-07-08 18:05
Might actually be related: https://github.com/mono/SkiaSharp/issues/1350

Seems linux is using some weird compressed text or something.

**Comment by Gillibald** [comment] 2020-07-08 18:09
This was measured properly with the current version (1.68.3) on the same system

**Comment by mattleibow** [comment] 2020-07-08 18:13
Yeah. Something changed in the linux rendering and measuring. Looking at that now. If you compare windows and linux, linux is more compressed.

**Comment by mattleibow** [comment] 2020-07-08 18:46
Interesting, I set the `SKPaint.IsLinearText = true` and now I get floating points on Linux and it now matches Windows.

Seems this triggers the original logic to do the advanced calc: https://github.com/google/skia/blob/chrome/m80/src/ports/SkFontHost_FreeType.cpp#L1062

Previously: https://github.com/google/skia/blob/chrome/m68/src/ports/SkFontHost_FreeType.cpp#L975

Seems to be the same logic... Maybe the defaults changed...

**Comment by mattleibow** [comment] 2020-07-08 19:11
@Gillibald I am having a look at this and it appears that v1.68.3 did not have floating point widths on Windows either. Seems the new functionality is to use floating points on Windows, but kept the original logic on Linux.

[TEST.zip](https://github.com/mono/SkiaSharp/files/4892749/TEST.zip)

**Comment by mattleibow** [comment] 2020-07-08 19:33
@Gillibald closing this as a duplicate of #1350

**Closed by mattleibow** 2020-07-08 19:33 UTC

**Comment by Gillibald** [comment] 2020-07-09 05:44
Setting `IsLinearText=true` works

**Comment by mattleibow** [comment] 2020-07-09 06:15
I am going to keep the other issue open so I can make sure I have a look at what happens in the latter versions of skia. Also, is the lunar part the new default. How does that affect things. Should we enable it by default...
