### ISSUE TITLE
[BUG] If SKCanvasView is inside CollectionView, PaintSurface is not called upon reusing CollectionView DataTemplate

### ISSUE THREAD

**Issue by zoli13** [mono/SkiaSharp#1226] opened 2020-04-10 18:51 UTC
**Description**

Having SKCanvasView in CollectionView in Xamarin.Forms causing not all items are displayed properly: when they are reused, InvalidateSurface() is not being called.

It happens only on iOS (tested on 13.4), on Android, it seems to work ok.
Tested on XF 4.5.0.617 and 4.5.0.530- both same
SkiaSharp.Views.Forms 1.68.1.1

**Code**

Open attached project, and run on iOS
[CollectionViewBug.zip](https://github.com/mono/SkiaSharp/files/4462946/CollectionViewBug.zip)

If you see the debug output log, you could also see that on iOS, after you scroll out the first page, it does not call SKCanvasViewIconListItem_PaintSurface to paint the new items scrolled into the view.
On Android, you could see that SKCanvasViewIconListItem_PaintSurface is called for every item as you scroll.

**Expected Behavior**

To display all items in CollectionView properly by calling SKCanvasViewIconListItem_PaintSurface  even on the reused items.

**Basic Information**

- Version with issue:  1.68.1.1
- IDE:  Visual Studio 16.5.3
- Platform Target Frameworks: 
  - iOS:  13.4

**Screenshots**

Android: OK, numbers are 1..150

![android](https://user-images.githubusercontent.com/9251057/79015206-9f72b280-7b6c-11ea-9195-bb982d06f874.png)

---------------------

iOS: NOT OK, after scrolling out first page and reaching number 40th, listitems are being reused, PaintSurface() is not called on them - so they display "old" drawings.

![ios](https://user-images.githubusercontent.com/9251057/79015264-baddbd80-7b6c-11ea-9ab4-d2e74497cdb1.png)

**Comment by mattleibow** [comment] 2020-04-10 21:51
Thanks for the detailed bug and the simple repro! Made it easy get testing.

This is technically "by design" because there is no way of the items knowing that they need to redraw. The case with Android is that it just works because the Android OS always redraws when a view moves or changes parent - when it is moved from the top of the list to the bottom. iOS is far less verbose and if nothing changes, then there is no need to redraw.

The simple way to do this is to just trigger a redraw on the binding change:

```xaml
<skia:SKCanvasView BindingContextChanged="SKCanvasViewIconListItem_BindingContextChanged" />
```

```csharp
private void SKCanvasViewIconListItem_BindingContextChanged(object sender, EventArgs e)
{
	(sender as SKCanvasView)?.InvalidateSurface();
}
```

**Comment by zoli13** [comment] 2020-04-11 13:30
Thanks the quick response, I had similar suspicion as well.
I tried the workaround, and it solves the problem - it works fine. Maybe should be called only on iOS, to prevent multiple redraw on Android? Although, Android implementation can also change by time, so maybe better to remain on the safe side...
As this is by "design", and there is a way to force the canvas to redraw, we should close?

**Comment by mattleibow** [comment] 2020-04-11 17:40
To make things easier for you, you can just create a custom control and use that:
```
public class AutoCanvasView : SKCanvasView
{
    protected override void OnBindingContextChanged()
    {
        base.OnBindingContextChanged();

        InvalidateSurface();
    }
}
```

Or you can look into creating a behaviour so that you can convert an event into a `Command` that you can use in the view model: https://dotnetdevaddict.co.za/2017/07/13/turning-events-into-commands/

```xaml
<views:SKCanvasView>
    <views:SKCanvasView.Behaviors>
        <local:PaintSurfaceCommandBehavior Command="{Binding PaintCommand}" />
    </views:SKCanvasView.Behaviors>
</views:SKCanvasView>
```

You can also combine the two to have a command and auto update:

```csharp
public class AutoCanvasView : SKCanvasView
{
    protected override void OnBindingContextChanged()
    {
        base.OnBindingContextChanged();

        InvalidateSurface();
    }

    public static readonly BindableProperty PaintCommandProperty =
        BindableProperty.Create(
            nameof(PaintCommand),
            typeof(ICommand),
            typeof(AutoCanvasView),
            null,
            propertyChanged: (b, o, n) => ((AutoCanvasView)b).InvalidateSurface());

    public ICommand PaintCommand
    {
        get => (ICommand)GetValue(PaintCommandProperty);
        set => SetValue(PaintCommandProperty, value);
    }

    protected override void OnPaintSurface(SKPaintSurfaceEventArgs e)
    {
        base.OnPaintSurface(e);

        if (PaintCommand?.CanExecute(e) == true)
            PaintCommand.Execute(e);
    }
}
```

**Comment by mattleibow** [comment] 2020-04-11 17:43
Closing this as it is by design to not trigger a redraw when the binding context changes.

**Closed** 2020-04-11 17:44 UTC
Labels: status-wontfix
