### ISSUE TITLE
[QUESTION] Unable to load shared library 'libSkiaSharp' or one of its dependencies.

### ISSUE THREAD

**Issue by IsoraTatsu** [mono/SkiaSharp#1422] opened 2020-07-20 09:31 UTC
**Exception**
```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)
   at SkiaSharp.QrCode.Image.QrCode..ctor(String content, Vector2Slim qrSize)
   at SkiaSharp.QrCode.Image.QrCode..ctor(String content, Vector2Slim qrSize, SKEncodedImageFormat outputFormat)
   at ...
```

```
<PackageReference Include="SkiaSharp.QrCode" Version="0.3.2" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.80.1" />
```

.net core 2.1, aws linux
Version with issue: 2.80.1

I had try to fix by
[https://github.com/mono/SkiaSharp/issues/964](url) but didn't work

**Comment by mattleibow** [comment] 2020-07-20 12:29
This was unfortunately a regression in 2.80.1 that will be fix in the next version coming soon: https://github.com/mono/SkiaSharp/issues/1341

You can try out `2.80.2-preview.2` right now on the preview feed: https://aka.ms/skiasharp-eap/index.json
I will be pushing this version to nuget.org very soon.

**Comment by mattleibow** [comment] 2020-07-20 12:30
Duplicate of #1341

**Closed by mattleibow** 2020-07-20 12:29 UTC
