### ISSUE TITLE
WinUI view not working on WindowsAppSdk 1.6

### ISSUE THREAD

**Issue by beto-rodriguez** [mono/SkiaSharp#3007] opened 2024-09-18 22:21 UTC
### Description

I am not able to run an app containing an SKXamlCanvas on WindowsAppSdk 1.6, not completely sure if the issue belongs to this library or to WindowsAppSdk.

### Code

Based on my research on:

https://github.com/beto-rodriguez/LiveCharts2/issues/1580

I can confirm that LiveCharts does not work on WindowsAppSdk 1.6, then I realized that even just the SKXamlCanvas does work on that version.

### Version of SkiaSharp

2.88.3 (Current)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Platform / Operating System Version

WindowsAppSdk 1.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by inforithmics** [comment] 2024-09-19 04:17
It is this issue, the Bug is fixed But a new SkiaSharp 3 nugget Release is needed.

https://github.com/mono/SkiaSharp/issues/2999

**Comment by mattleibow** [comment] 2024-09-30 03:13
Can you try the latest nightly on `https://aka.ms/skiasharp-eap/index.json` and let me know if it starts working again? I want to do a release, but I want to make sure I fixed it.

**Comment by Mangepange** [comment] 2024-10-02 06:46
@mattleibow Using the latest Microsoft.WindowsAppSDK, v1.6.240923002:

SkiaSharp.Views.WinUI 3.0.0-nightly.263 - Not working
SkiaSharp.Views.WinUI 3.0.0-nightly.265 and newer - Works
SkiaSharp.Views.WinUI 3.0.0-preview.5.1 and newer - Works

I guess that it's not yet backported into SkiaSharp 2, since the latest nightly version (2.88.9-nightly.176) does not work.

**Comment by beto-rodriguez** [comment] 2024-10-02 07:48
@mattleibow I read in another issue that this fix might not be ported to 2.x, is that true?

**Comment by Mangepange** [comment] 2024-10-03 07:04
@beto-rodriguez Ouch, where did you see that information?

**Comment by Bush-cat** [comment] 2024-10-03 11:04
> Since that is still preview and SkiaSharp is stable, I cannot really depend on it for SkiaSharp 2.x. However, the 2.x branch does not have the convenient native library that I can use. I technically can add it to 2.x but that is a lot of work, and that old branch is very iffy to build.
> [microsoft/CsWinRT#1645 (comment)](https://github.com/microsoft/CsWinRT/issues/1645#issuecomment-2211241512)

**Comment by Mangepange** [comment] 2024-10-10 08:00
Does anybody know if there are any plans for when a stable version of SkiaSharp 3 is released?

**Comment by ArpitViradiyaCrowncon** [comment] 2024-10-10 09:19
When SkiaSharp 3 is released?

**Comment by Mangepange** [comment] 2024-10-10 10:00
> When SkiaSharp 3 is released?

Yes, just wondering since it doesn't seems to be sure that the fix for this issue will be backported into v2.

**Comment by ArpitViradiyaCrowncon** [comment] 2024-10-10 10:02
> > When SkiaSharp 3 is released?
> 
> Yes, just wondering since it doesn't seems to be sure that the fix for this issue will be backported into v2.

So how can we resolved this issue?

**Comment by ArpitViradiyaCrowncon** [comment] 2024-10-10 10:51
> > > Yes, just wondering since it doesn't seems to be sure that the fix for this issue will be backported into v2.
> > 
> > 
> > So how can we resolved this issue?
> 
> See #2999. It's fixed in SkiaSharp 3.

I think that' for WinUi, I want for .Net maui. In nuget I can only show 
`<PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc3.3" />`

**Comment by mattleibow** [comment] 2024-10-25 16:29
Closing this for now as the issue is fixed for both v2 and v3 in the latest preview.

**Closed** 2024-10-25 16:29 UTC
Labels: type/bug
