### ISSUE TITLE
Unable to create Euclid Flex Thin font

### ISSUE THREAD

**Issue by VijayRM** [mono/SkiaSharp#1272] opened 2020-05-05 13:27 UTC
Unable to create **Euclid Flex Thin** font. I have used below code.
`SKTypeface typeFace = SKTypeface.FromFamilyName(@"Euclid Flex", SKFontStyleWeight.Thin, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);`

If we save the stream as a file, it shows the font name **Euclid Flex Ultralight**.

```
FileStream fontStream = new FileStream(@"D:\EuclidFont.otf", FileMode.Create, FileAccess.Write);  
  SKStreamAsset stream = typeFace.OpenStream();
            if (stream != null && stream.Length > 0)
            {
                byte[] fontData = new byte[stream.Length - 1];
                stream.Read(fontData, stream.Length);
                stream.Dispose();
                MemoryStream m_stream = new MemoryStream(fontData);
                m_stream.CopyTo(fontStream);
                fontStream.Flush();
            }
```

SkiaSharp version - 1.59.3
NET Core 2.0

**Comment by mattleibow** [comment] 2020-05-05 15:08
The `SKTypeface.FromFamilyName()` requires that the font be installed to the system (C:\Windows\Fonts)

If you don't have permissions or can't install, then reading from a stream is just fine. There are other options to load without copying:
 - `SKTypeface.FromFile`
 - SKTypeface.FromStream

**Comment by VijayRM** [comment] 2020-05-05 15:14
Yes this font was already installed.

**Comment by mattleibow** [comment] 2020-05-05 15:51
It might be because you are querying the font weight as `SKFontStyleWeight.Thin` or using `SKFontStyleWidth.Normal`.

I think this is a duplicate of #682

**Comment by VijayRM** [comment] 2020-05-06 05:35
SKFontStyleWeight.Light is working for the same font. So, this issue occurs only for SKFontStyleWeight.Thin. Whether it is a known bug of SkiaSharp?

**Comment by mattleibow** [comment] 2020-05-06 07:37
I'm closing this now because it is a duplicate of #682. Not a bug per se, but definitely a known limitation. This is something we can address in the upcoming v2 of the library.

I'll update the other issue with progress, so it might be good to subscribe to that one.

**Closed by mattleibow** 2020-05-06 07:37 UTC
