### ISSUE TITLE
Enable font subsetting for PDFs through Harfbuzz

### ISSUE THREAD

**Issue by Bebo-Maker** [mono/SkiaSharp#2180] opened 2022-07-21 19:14 UTC
Related issues: #848

PDFs generated with SkiaSharp are very large in size.
The root cause of this issue seems to be, that Skia embeds all used fonts inside the document, [as stated here](https://skia.org/docs/dev/design/pdftheory/#fonts).

Fonts contain information for a lot of characters. However most of the time, there is only a small percentage of these characters that is actually needed to display the document correctly.
Subsetting these fonts would reduce the size of the font files drastically, which would result in much smaller PDFs.

Looking at Skia`s source code ([SkPDFSubsetFont](https://github.com/google/skia/blob/1f193df9b393d50da39570dab77a0bb5d28ec8ef/src/pdf/SkPDFSubsetFont.cpp#L10)) there seems to be a way to automatically subset all used fonts inside a PDF document with harfbuzz ("SK_PDF_USE_HARFBUZZ_SUBSET"). [This line](https://github.com/google/skia/blob/1f193df9b393d50da39570dab77a0bb5d28ec8ef/BUILD.gn#L1114) seems to enable the subsetting support.

Other Skia binding libraries (Skiko, [Rust-Skia](https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build_support/skia/config.rs#L157)) seem to enable this flag, which results in a much smaller PDFs. I can provide some example PDF files (with and without subsetting) generated with these libraries if someone wants to take a look at it.

Would be great if we could enable this for SkiaSharp. I am not familar with the build system, but there should be a way to specify this flag, right? Maybe [here](https://github.com/mono/SkiaSharp/blob/main/native/windows/build.cake#L45)?

By the way, [QuestPDF](https://github.com/QuestPDF/QuestPDF) uses SkiaSharp for PDF document generation and smaller pdf file sizes is one of the [most requested features](https://github.com/QuestPDF/QuestPDF/issues/31), so it would be great to have this.

**Comment by rnight** [comment] 2022-07-26 03:37
That's great!
I hope so, too.

**Comment by MarcinZiabek** [comment] 2022-07-30 14:55
As the author of the QuestPDF library, I really think that this feature would help the entire community. Thank you @Bebo-Maker for creating this feature request.

**Comment by mattleibow** [comment] 2022-08-12 10:56
Duplicate of #848

**Closed by mattleibow** 2022-08-12 10:56 UTC
