### ISSUE TITLE
[BUG] UIWebView still used in Mono and SkiaSharp

### ISSUE THREAD

**Issue by florian-berger** [mono/SkiaSharp#1534] opened 2020-10-19 13:16 UTC
**Description**

From december 2020, Apple rejects all app store submissions, that are using the deprecated UIWebView instead of WKWebView. SkiaSharp is one of the libraries, that are still referencing this deprecated API.

From december, it is no longer possible to update an existing app that includes this reference.

**Code**

**Expected Behavior**

libSkiaSharp must not reference UIWebView

**Actual Behavior**

libSkiaSharp is referencing UIWebView

**Basic Information**

- Version with issue:  2.80.2
- Last known good version:  none
- IDE:  Visual Studio Enterprise 2019, Version 16.7.6 | Xamarin.iOS 14.0.0.0
- Platform Target Frameworks: 
  - Android: Xamarin.Android SDK 11.0.2.0
  - iOS:  Xamarin.iOS 14.0.0.0
  - Linux:  -
  - macOS:  -
  - Tizen:  -
  - tvOS:  -
  - UWP:  -
  - watchOS:  -
  - Windows Classic:  -
- Target Devices:   
  - 
  - 
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

SkiaSharp 2.80.2
SkiaSharp.Views.Forms 2.80.2

```
</details>

**Screenshots**

![image](https://user-images.githubusercontent.com/10084586/96454550-4e7aff80-121c-11eb-9154-eabebb18af0e.png)

**Comment by mattleibow** [comment] 2020-10-20 23:35
Duplicate of https://github.com/mono/SkiaSharp/issues/1271

**Comment by mattleibow** [comment] 2020-10-20 23:40
I had a look again, and SkiaSharp does not reference any UIKit types. Not sure what type of build this is, but there should be no reference at all.

I think the script is misleading you. The script is always printing the framework name, but actually does not reference it

When trying to look for `UIWebView`

**script**
```
for framework in Frameworks/*.framework; do
fname=$(basename $framework .framework)
echo $fname
nm $framework/$fname | grep UIWebView
done
```

**output**
```
libSkiaSharp
```

When trying to look for `wstream`


**script**
```
for framework in Frameworks/*.framework; do
fname=$(basename $framework .framework)
echo $fname
nm $framework/$fname | grep wstream
done
```

**output**
```
libSkiaSharp
0000000000009620 T _sk_dynamicmemorywstream_copy_to
0000000000009580 T _sk_dynamicmemorywstream_destroy
0000000000009600 T _sk_dynamicmemorywstream_detach_as_data
00000000000095e0 T _sk_dynamicmemorywstream_detach_as_stream
00000000000095a0 T _sk_dynamicmemorywstream_new
0000000000009630 T _sk_dynamicmemorywstream_write_to_stream
0000000000009520 T _sk_filewstream_destroy
0000000000009570 T _sk_filewstream_is_valid
0000000000009540 T _sk_filewstream_new
000000000000223e T _sk_managedwstream_destroy
00000000000021ff T _sk_managedwstream_new
0000000000002250 T _sk_managedwstream_set_procs
0000000000009680 T _sk_wstream_bytes_written
0000000000009670 T _sk_wstream_flush
00000000000097e0 T _sk_wstream_get_size_of_packed_uint
0000000000009650 T _sk_wstream_newline
0000000000009640 T _sk_wstream_write
00000000000096c0 T _sk_wstream_write_16
00000000000096f0 T _sk_wstream_write_32
0000000000009690 T _sk_wstream_write_8
0000000000009750 T _sk_wstream_write_bigdec_as_text
0000000000009780 T _sk_wstream_write_bool
0000000000009740 T _sk_wstream_write_dec_as_text
0000000000009760 T _sk_wstream_write_hex_as_text
00000000000097c0 T _sk_wstream_write_packed_uint
00000000000097b0 T _sk_wstream_write_scalar
0000000000009770 T _sk_wstream_write_scalar_as_text
00000000000097d0 T _sk_wstream_write_stream
0000000000009710 T _sk_wstream_write_text
```

**Closed by mattleibow** 2020-10-20 23:40 UTC

**Comment by idimkk** [comment] 2020-11-09 15:00
Were you able to solve this problem?
I am still getting consistent rejections from Apple due to this link.
I will be glad for your help!

@florian-berger
