### ISSUE TITLE
Deploying ASP.NET website using SkiaSharp and libSkikSharp.dll in Windows Server 2012 shows "BadImageFormatException". This is probably due to wrong bit of the libSkiaSharp.dll. I have tried replacing with dlls of win7, win 10 (32-bit and 64-bit). How do I resolve this issue?

### ISSUE THREAD

**Issue by atuladhar** [mono/SkiaSharp#586] opened 2018-07-23 09:31 UTC
### Basic Information

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:
  -

**Comment by ojb500** [comment] 2018-07-24 09:46
Hi @atuladhar 

You can try to set the ```PreferredNativeSkiaSharp``` msbuild property to the correct bitness for your deployment

```
<PropertyGroup>
  <PreferredNativeSkiaSharp>x86</PreferredNativeSkiaSharp>
</PropertyGroup>
```

**Comment by atuladhar** [comment] 2018-07-25 08:02
Thanks.. added this to my .csproj file but still I have the same error.

**Comment by Remolutionary** [comment] 2018-10-16 07:14
Having the same issue on Windows Server 2012 R2. Is there maybe a workaround? 
@ojb500 Did you find a solution?

**Comment by Remolutionary** [comment] 2018-10-16 09:41
The problem does not occur on Windows Server 2016.

**Comment by atuladhar** [comment] 2018-10-17 07:15
No, the problem isn't resolved yet in Window Server 2012.

**Comment by mattleibow** [comment] 2018-11-30 18:31
Duplicate of #513 #572 #579

**Closed by mattleibow** 2018-11-30 18:31 UTC
