### ISSUE TITLE
Missing copyright and file version information on native binaries libSkiaSharp.dll and libHarfBuzzSharp.dll

### ISSUE THREAD

**Issue by pinzart90** [mono/SkiaSharp#2806] opened 2024-03-25 19:01 UTC
### Description

Native binaries from HarfBuzzSharp.NativeAssets.Win32 are missing copyright and file version information
Native binaries from SkiaSharp.NativeAssets.Win32 are missing copyright and file version information
![image](https://github.com/mono/SkiaSharp/assets/46732933/0bc0191e-cdbc-4c3a-844f-c8011c28d6c4)

### Code

The best way to share code for larger projects is a link to a GitHub repository: https://github.com/user/repo/tree/bug-123

But, you can also share a short block of code here:
```cs
// some C# code here
```
You can also share some XAML:
```xaml
<!-- xaml code here -->
```

### Expected Behavior

Native assemblies in published nuget packages should have copyright and file version information

### Actual Behavior

Native binaries from packages HarfBuzzSharp.NativeAssets.Win32 and SkiaSharp.NativeAssets.Win32 do not have copyright and file version information

### Version of SkiaSharp

3.x (Alpha)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

Windows

### Relevant Screenshots

![image](https://github.com/mono/SkiaSharp/assets/46732933/63f59c07-9c58-40b4-857b-25ed12171c25)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment] 2024-03-27 20:10
Duplicate of https://github.com/mono/SkiaSharp/issues/2507

**Closed by mattleibow** 2024-03-27 20:10 UTC
Labels: type/bug
