### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: 

### ISSUE THREAD

**Issue by dandanyouxiang** [mono/SkiaSharp#2187] opened 2022-07-25 08:16 UTC
[App.zip](https://github.com/mono/SkiaSharp/files/9179416/App.zip)
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibSkiaSharp: cannot open shared object file: No such file or directory
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKImageInfo..ctor(Int32 width, Int32 height)
   at App.Program.Main(String[] args) in C:\Users\Tom\Downloads\SkiaSharp-main\samples\Basic\NetCore\Console\App\Program.cs:line 13

**This problem occurs when I run under Linux(Loongson-3A40000)**

**Using the following method is the same problem**
`<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="2.88.0" />
<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.0" />
`

**Comment by dandanyouxiang** [comment] 2022-07-25 09:09
![image](https://user-images.githubusercontent.com/12132063/180741046-691b9bd9-a011-465f-9516-c76ead76beab.png)

Run Ubuntu is OK

**Comment by zxh126** [comment] 2022-08-08 01:16
Add Package SkiaSharp.NativeAssets.Linux or SkiaSharp.NativeAssets.Linux.NoDependencies.

**Comment by mattleibow** [comment] 2022-08-12 19:27
Duplicate of #1999

**Closed by mattleibow** 2022-08-12 19:27 UTC
