### ISSUE TITLE
[BUG] Measuring width is different in the Higher SkiaSharp version for Linux Docker environment

### ISSUE THREAD

**Issue by MadhanKumarasamy** [mono/SkiaSharp#1435] opened 2020-07-30 12:48 UTC
**Description**

I am using a SkiaSharp library for measuring the text and I have recently upgraded the SkiaSharp library version [2.80.0]. Then I try to measure the text in the Higher version and its text width different from the older version. kindly provide your suggestion to resolve this issue.

**Code**

```
SKBitmap bmp = new SKBitmap(120, 120, SKImageInfo.PlatformColorType, SKAlphaType.Premul);
            float skiaMeasurement = 0;
            SKCanvas canvas = new SKCanvas(bmp);
            canvas.Clear(SKColors.White);
            using (SKPaint paint = new SKPaint())
            {
                paint.Typeface = SKTypeface.FromFamilyName("Cambria", SKFontStyleWeight.Bold, SKFontStyleWidth.Normal, SKFontStyleSlant.Upright);
                //paint.Typeface = SKTypeface.FromFile("CustomFonts\times.ttf");
                paint.Color = SKColors.Black;
                paint.IsAntialias = true;
                paint.TextSize = 11f;
                paint.SubpixelText = true;
                paint.TextAlign = SKTextAlign.Left;
                paint.TextEncoding = SKTextEncoding.Utf8;
                SKRect rect = new SKRect();
                skiaMeasurement = paint.MeasureText("this certificate", ref rect);
                Console.WriteLine("SKia Width = " + skiaMeasurement);
            }
```

**Expected Behavior**

SKia Width = 72

**Actual Behavior**

SKia Width = 73.00391

**Basic Information**

- Version with issue:  2.80.0
- Last known good version:  1.59.3
- IDE:  Visual Studio 2017
- Platform Target Frameworks: .NET Core 3.0
  - Windows OS: Linux Docker

**Comment by mattleibow** [comment] 2020-07-31 21:56
Closing this as most probably a duplicate of #1350

**Closed** 2020-07-31 21:56 UTC
