### ISSUE TITLE
[BUG] SkiaSharp.View.Uno.WinUI incompatible with other NativeReference (here storj_uplink)

### ISSUE THREAD

**Issue by TopperDEL** [mono/SkiaSharp#2105] opened 2022-06-08 13:14 UTC
**Description**
I'm developing a Uno-App that uses the Storj-network with an open source library called [uplink.NET](https://github.com/TopperDEL/uplink.net), that needs a specific binary: storj_uplink.framework. If I have both nugets Skiasharp.Views.Uno.WinUI and [uplink.NET.iOs](https://www.nuget.org/packages/uplink.NET.iOS/) in a Mobile-project, I get the following error:

``
1>C:\Users\Toppe\.nuget\packages\skiasharp.nativeassets.ios\2.88.1-preview.63\buildTransitive\net6.0-ios13.6\SkiaSharp.NativeAssets.iOS.targets(6,9): error MSB4096: Das Element "C:\Users\Toppe\.nuget\packages\uplink.net.ios\2.9.2659\build\net6.0-ios\storj_uplink.framework" in der Elementliste "NativeReference" definiert keinen Wert für die Metadaten "FrameworkFilename".  Wenn Sie diese Metadaten verwenden möchten, qualifizieren Sie sie, indem Sie %(NativeReference.FrameworkFilename) angeben, oder vergewissern Sie sich, dass alle Elemente in der Liste einen Wert für diese Metadaten definieren.``

It basically says, that the storj_uplink.framework within the ElementList "NativeReference" does not include the Metadata-element "FrameworkFilename". The error points to the Skiasharp.NativeAssets.iOs.targets-file. If I understand correctly it verifies the native assets from Skiasharp to have a certain naming pattern. But that should not check other native assets, I think. At least I'm not sure how I can overcome this issue.

The storj_uplink.framework can be found [here](https://github.com/TopperDEL/uplink.net/tree/master/nuspec/xamarinios).

**Code**

**Expected Behavior**
I can use both Nugets together without issues.

**Actual Behavior**
The SkiaSharp-packages cannot work with the uplink.NET-package.

**Basic Information**

- Version with issue:  2.88.1-preview.63
- IDE:  Visual Studio
- Platform Target Frameworks: 
  - iOS:  latest

**Comment by TopperDEL** [comment] 2022-06-08 13:28
I've added the "<FrameworkFilename>" metadata to the uplink.NET.iOs-package and the next error arises. It also wants to have the NugetPackageId attached.

I'm trying this next and if that works it would be ok for me for the moment. But that check should still only be necessary for Skiasharp-Nativereferences.

**Comment by TopperDEL** [comment] 2022-06-08 18:18
Next one is "NuGetPackageVersion".

**Comment by TopperDEL** [comment] 2022-06-08 19:04
And "AssetType".

**Comment by mattleibow** [comment] 2022-06-09 06:23
Thanks for reporting and the comments! Can you attach a binlog so I can check why other frameworks are being included? I believe the filename should be explicitly libSkiaSharp, so maybe my conditions are incorrect.

**Comment by TopperDEL** [comment] 2022-06-09 06:34
Is a binlog in this case the output from the build window in visual studio? I've set it to detailled, but now it is 60MB in size... :)

**Comment by roberleitner** [comment] 2022-07-20 21:31
@mattleibow i hit this in my ios project which has its own native references. after added a reference to skiasharp 2.88.0, the checks in [SkiaSharp.NativeAssets.iOS.targets](https://github.com/mono/SkiaSharp/blob/main/binding/SkiaSharp/nuget/build/ios/SkiaSharp.targets) cause my build to fail because my native reference didn't define the properties you are referencing. 

```
Target "_SkiaSharpExpandNativeReferencesFixes" in file "/Users/REDACTED/.nuget/packages/skiasharp.nativeassets.ios/2.88.0/buildTransitive/net6.0-ios13.6/SkiaSharp.NativeAssets.iOS.targets":
  /Users/REDACTED/.nuget/packages/skiasharp.nativeassets.ios/2.88.0/buildTransitive/net6.0-ios13.6/SkiaSharp.NativeAssets.iOS.targets(6,9): error MSB4096: The item "Native References/REDACTED.framework" in item list "NativeReference" does not define a value for metadata "FrameworkFilename".  In order to use this metadata, either qualify it by specifying %(NativeReference.FrameworkFilename), or ensure that all items in this list define a value for this metadata.
Done building target "_SkiaSharpExpandNativeReferencesFixes" in project "REDACTED.Mobile.iOS.csproj" -- FAILED.
```

is this check even needed anymore? the issue [11667](https://github.com/xamarin/xamarin-macios/issues/11667) linked in the comment has since been resolved.

obviously i'm able to work around by adding those properties but would rather not.

happy to supply any logs that can help but the lines above are the only useful mention i see of _SkiaSharpExpandNativeReferencesFixes in the build output.

**Comment by mattleibow** [comment] 2022-08-04 11:21
Thanks for all this info, closing this as a duplicate of #1879

I will use that issue to track the fix. Hopefully this is just a removal of the hack since the bug in iOS/macOS has been fixed!

**Closed by mattleibow** 2022-08-04 11:21 UTC
