### ISSUE TITLE
[iOS, 3.0 Preview 4.1] SkiaSharp on iOS has a severe memory leak in .NET MAUI 9.0 Preview 6 (Test App Provided)

### ISSUE THREAD

**Issue by janne-hmp** [mono/SkiaSharp#2951] opened 2024-07-19 21:15 UTC
### Description

On iOS, if one opens successively many pages with bitmaps drawn with SKCanvasView, SkiaSharp crashes in a memory leak. I tested this now with SkiaSharp 3.0 Preview 4.1 and .NET MAUI 9.0 Preview 6. Other platforms work fine.

I made a test app based on default MAUI project through which this can be automatically tested. Just press the Click Me button, which starts opening and closing pages. Since pages are always closed, this should not cause the app to run out of memory.

In my case with an old iPad (11,7), it ran out of memory after opening the same page c. 145 times.

@mattleibow Can you please download the app, and let me know what you see yourself?

### Code

The sample app repository is here (just change the provisioning):

https://github.com/hyvanmielenpelit/iOSMauiSkiaSharpMemoryLeak

### Expected Behavior

The app can open the page all 500 times.

### Actual Behavior

On iPad 11,7, the app crashes after opening and closing the page c. 145 times.

### Version of SkiaSharp

3.x (Alpha)

### Last Known Good Version of SkiaSharp

Other (Please indicate in the description)

### IDE / Editor

Visual Studio (Windows)

### Platform / Operating System

iOS

### Platform / Operating System Version

iOS 17.5.1

### Devices

iPad 11,7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattleibow** [comment] 2024-07-23 22:19
Duplicate of https://github.com/mono/SkiaSharp/issues/2923

**Closed by mattleibow** 2024-07-23 22:19 UTC
Labels: type/bug
