### ISSUE TITLE
Unable to load shared library 'libSkiaSharp' - Alpine Linux 3.16 - SkiaSharp.NativeAssets.Linux.NoDependencies 2.88.0

### ISSUE THREAD

**Issue by JMan7777** [mono/SkiaSharp#2215] opened 2022-08-14 08:21 UTC
Hello, 

I'm getting the error described below, as it looks like the libSkiaSharp.so file is not found.

The file is actually automatically deployed into the docker container but I don't know why it is not loaded/found:

**_Debug environment:_**
_/app/bin/Debug/netcoreapp3.1/runtimes/linux-musl-x64/native/libSkiaSharp.so_
_/app/bin/Debug/netcoreapp3.1/runtimes/linux-x64/native/libSkiaSharp.so_

_**Prod environment:**_
_/app/bin/Release/netcoreapp3.1/runtimes/linux-musl-x64/native/libSkiaSharp.so_
_/app/bin/Release/netcoreapp3.1/runtimes/linux-x64/native/libSkiaSharp.so_

**Error:**
-----------

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKData' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory
   at SkiaSharp.SkiaApi.sk_data_new_empty()
   at SkiaSharp.SKData..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKData.Create(Stream stream)
   at SkiaSharp.SKImage.FromEncodedData(Stream data)
```

**Used SkiaSharp package:**
-------------------------------
SkiaSharp.NativeAssets.Linux.NoDependencies 
(Version 2.88.0)

**Environment:**
-------------------
Azure Linux Web App running in Docker Container.

**.NET Core version:**
-------------------
3.1.28

**Docker Base Image:**
-------------------
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine AS base
(v3.16 is the underlying Alpine Linux version)

**Other Alpine packages added (required for other functionalities)**
--------------------------------------------------------------------
RUN apk add --no-cache icu-libs
RUN apk add --no-cache libgdiplus --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --allow-untrusted
RUN apk add --no-cache chromium  
RUN apk add --no-cache chromium-chromedriver 
RUN apk add --no-cache tini

Thx for your help.

_**PS:**_ 
It was working long time ago with some older .NET Core 3.1.x version, Alpine 3.x version and SkiaSharp.NativeAssets.Linux.NoDependencies version, but I can't say which version upgrade broke it.

**Comment by mattleibow** [comment] 2022-08-14 11:52
Duplicate of #2169

Unfortunately, there is an issue with the dotnet on the alpine images. They can't load any native binaries since 3.15. See the linked issue as well for workarounds.

**Closed** 2022-08-14 11:55 UTC

**Comment by mattleibow** [comment] 2022-08-14 11:58
Filed this issue to hopefully get it fixed: https://github.com/dotnet/sdk/issues/27156
