### ISSUE TITLE
[BUG] SkiaSharp crashes application MAUI

### ISSUE THREAD

**Issue by mgood7123** [mono/SkiaSharp#1979] opened 2022-03-22 13:25 UTC
having

```CS
namespace SkiaUI;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
		Content = new SkiaSharp.Views.Maui.Controls.SKCanvasView();
	}
}
```

causes MAUI App (Preview) to crash at startup with unhandled exception in debugger

commenting out `Content = new SkiaSharp.Views.Maui.Controls.SKCanvasView();` makes the error go away but then we have no Skia View

how can this be worked around?

[Project That Crashes SkiaUI.zip](https://github.com/mono/SkiaSharp/files/8324617/SkiaUI.zip)

im using

```
Visual Studio 2022 Windows - Version 17.2.0 Preview 2.0

C:\Users\matthew good\.nuget\packages\microsoft.graphics.win2d\1.0.0.30\
C:\Users\matthew good\.nuget\packages\microsoft.maui.dependencies\6.0.200-preview.14.5099\
C:\Users\matthew good\.nuget\packages\microsoft.maui.extensions\6.0.200-preview.14.5099\
C:\Users\matthew good\.nuget\packages\microsoft.windowsappsdk\1.0.0\
C:\Users\matthew good\.nuget\packages\skiasharp.views.maui.controls\2.88.0-preview.232\
```

EDIT:
now having `SkiaSharp.Views.Maui.Controls.SKGLView` crashes the application, even if `SKCanvasView` does not crash

**Comment by mgood7123** [comment] 2022-03-23 00:44
> @mgood7123 Can you provide a bit more info on what exception and which platforms?
> 
> Maybe a stack trace?

all i get is this

![image](https://user-images.githubusercontent.com/26642847/159599752-34385a2e-f1c4-4c4f-a19a-54126b70922c.png)

**Comment by mgood7123** [comment] 2022-04-02 04:33
any updates?

**Comment by mgood7123** [comment] 2022-04-09 09:01
is more information needed?

**Comment by xtuzy** [comment] 2022-04-11 02:08
I run your example, you don't set this according to sample:
https://github.com/mono/SkiaSharp/blob/b7728fae36218ee5204e0dc7c48cb2022099a8a4/samples/Basic/Maui/SkiaSharpSample/MauiProgram.cs#L13

**Comment by mgood7123** [comment] 2022-04-14 06:26
> I run your example, you don't set this according to sample:
> 
> https://github.com/mono/SkiaSharp/blob/b7728fae36218ee5204e0dc7c48cb2022099a8a4/samples/Basic/Maui/SkiaSharpSample/MauiProgram.cs#L13

i cant find much documentation on google

https://www.google.com/search?q=%22UseSkiaSharp%28true%29%22&client=firefox-b-d&sxsrf=APq-WBvaNCThOGIzDce4F2EjDPJZUkh0qw%3A1649917531137&ei=W75XYuCGCPyeseMPl7iQiAw&ved=0ahUKEwigoOji9ZL3AhV8T2wGHRccBMEQ4dUDCA0&uact=5&oq=%22UseSkiaSharp%28true%29%22&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6CAgAEA0QBRAeOggIABAIEA0QHkoECEEYAEoECEYYAFDxB1ioE2C-FWgBcAF4AIAB1gGIAakJkgEFMC4zLjOYAQCgAQHIAQjAAQE&sclient=gws-wiz

**Comment by mgood7123** [comment] 2022-04-14 12:58
> Maui is new ,something not same as Xamarin.Form, so according sample to do is better

alright

**Comment by mgood7123** [comment] 2022-04-14 12:59
is resizing a MAUI SkiaSharp view as insanely fast as resizing a Windows Forms SkiaSharp view? or is it as slow as resizing an Xamarin.Form SkiaSharp view?

**Comment by xtuzy** [comment] 2022-04-14 13:58
> is resizing a MAUI SkiaSharp view as insanely fast as resizing a Windows Forms SkiaSharp view? or is it as slow as resizing an Xamarin.Form SkiaSharp view?

slow? i don't compare they, you can try not use xamarin.form or maui, just use skiasharp in xamarin native to compare, that will let you know where is low. if xamarin native also slow, you can use gpu, or you can get some suggest form [react-native-skia](https://github.com/Shopify/react-native-skia)

**Comment by mgood7123** [comment] 2022-04-19 04:42
> > is resizing a MAUI SkiaSharp view as insanely fast as resizing a Windows Forms SkiaSharp view? or is it as slow as resizing an Xamarin.Form SkiaSharp view?
> 
> slow? i don't compare they, you can try not use xamarin.form or maui, just use skiasharp in xamarin native to compare, that will let you know where is low. if xamarin native also slow, you can use gpu, or you can get some suggest form [react-native-skia](https://github.com/Shopify/react-native-skia)

or rather, i should say that

resizing a SkiaSharp Universal Windows app is noticably slow/laggy

resizing a SkiaSharp Windows Forms app is instant even under rapid resizing

**Comment by mgood7123** [comment] 2022-04-19 20:32
ok, so MAUI is a bit faster than Universal Windows app when resizing

but nowhere near as fast as Windows Forms is

**Comment by mgood7123** [comment] 2022-04-19 20:58
anyone know why `SKGLView` crashes?

i have `UseSkiaSharp()` in my `MauiProgram.cs`

**Comment by mgood7123** [comment] 2022-04-20 03:33
[MauiApp1.zip](https://github.com/mono/SkiaSharp/files/8518110/MauiApp1.zip)

this is my current app in which `SKGLView` crashes if i try to use it, `SKCanvasView` works fine tho

**Comment by mgood7123** [comment] 2022-04-20 10:26
the error is same as last time too, unhandled win32 exception

**Comment by mgood7123** [comment] 2022-04-22 05:04
a temporary workaround is to use a non-MAUI app (eg WPF ) directly when targeting Windows, and MAUI when targeting other platforms

**Comment by xtuzy** [comment] 2022-05-14 01:05
SKGLView not support WinUI, see https://github.com/mono/SkiaSharp/pull/1678

**Comment by mdbill** [comment] 2022-06-18 19:40
> .UseSkiaSharp(true)

I also wasted at least an hour debugging, and this ^^ fixes it.  Thx!  a better errormsg or warning would be nice.

**Comment by mgood7123** [comment] 2022-09-03 05:26
I'm going to leave this open until a better solution exists that let's users know they forgot to add UseSkiaSharp

**Comment by mattleibow** [comment] 2023-09-06 14:40
Duplicate of #2050

**Closed by mattleibow** 2023-09-06 14:40 UTC
Labels: area/SkiaSharp.Views.Maui
