### ISSUE TITLE
Svg Colors incorrect since SkiaSharp 1.57.1 on some Android devices

### ISSUE THREAD

**Issue by michelmoorlag** [mono/SkiaSharp#300] opened 2017-05-23 06:30 UTC
I tested two libraries ffimagedloading and XamaRed.Forms.Svg to show svg images in Xamarin Forms.
Both use SkiaSharp and both worked fine up to SkiaSharp 1.56.1. After SkiaSharp 1.57.1 was released colors of svg images on some android devices are messed up.
See:
https://github.com/luberda-molinet/FFImageLoading/issues/605
and
https://github.com/Brainflab/XamaRed.Forms.Svg/issues/3#issuecomment-301759899

**Comment by michelmoorlag** [comment] 2017-05-23 07:34
I did more tests. I upgraded step bij step and this issue was introduced between 1.56.1 and 156.2.
So 1.56.1 all is fine:

![color1](https://cloud.githubusercontent.com/assets/14913939/26342982/7e39dbe0-3f9a-11e7-8a6d-1a0a0ab9cac1.JPG)

With 1.56.2 colors are messed up:

![color2](https://cloud.githubusercontent.com/assets/14913939/26342865/0ed066b6-3f9a-11e7-8763-eed06579173d.JPG)
I added a small example solution
[SvgTest (2).zip](https://github.com/mono/SkiaSharp/files/1021289/SvgTest.2.zip)

**Comment by mattleibow** [comment] 2017-05-23 15:27
Thanks for this issue. I am looking at this now. Not quite sure exactly what is going on, but I think that your observation of the change in v1.56.1 and 1.56.2 helps out a great deal. I was thinking the Google changed something, but it now appears that there may be some issue with the way in which the SVG is drawn.

Closing this one as I believe it is a duplicate of #284  If you want to follow the progress, you can just watch that issue.

**Closed by mattleibow** 2017-05-23 15:27 UTC

**Comment by mattleibow** [comment] 2017-06-30 22:22
Just pushed out a release that should resolve this: https://github.com/mono/SkiaSharp/releases/tag/v1.58.1
