### ISSUE TITLE
[BUG] Unable to use skiasharp.views.forms in .Net Framework 4.7.2

### ISSUE THREAD

**Issue by Kobsky** [mono/SkiaSharp#1523] opened 2020-10-07 06:33 UTC
**Description**

My unit tests project's based on .net Framework 4.7.2 and I got a missing assembly error after update skiasharp.views.forms from old version.

**Code**

To reproduce this defect, create a .net class library.
Add NuGet packages:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="OpenTK" version="3.1.0" targetFramework="net472" />
  <package id="OpenTK.GLControl" version="3.1.0" targetFramework="net472" />
  <package id="SkiaSharp" version="2.80.2" targetFramework="net472" />
  <package id="SkiaSharp.Views" version="2.80.2" targetFramework="net472" />
  <package id="SkiaSharp.Views.Desktop.Common" version="2.80.2" targetFramework="net472" />
  <package id="SkiaSharp.Views.Forms" version="2.80.2" targetFramework="net472" />
  <package id="SkiaSharp.Views.Gtk2" version="2.80.2" targetFramework="net472" />
  <package id="SkiaSharp.Views.WindowsForms" version="2.80.2" targetFramework="net472" />
  <package id="SkiaSharp.Views.WPF" version="2.80.2" targetFramework="net472" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.3" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" targetFramework="net472" />
  <package id="Xamarin.Forms" version="4.6.0.800" targetFramework="net472" />
</packages>
```

and just create a simple class

```
using SkiaSharp.Views.Forms;

namespace ClassLibrary1
{
    public class Class1
    {
        private SKCanvasView _canvasView;
    }
}
```

Try to build and got a build failure.

**Expected Behavior**

Build successful 

**Actual Behavior**

Build failure

**Basic Information**

- Version with issue:  2.80.2
- Last known good version:  1.68.0 
- IDE:   Visual Studio 
- Platform Target Frameworks: 
  - Windows Classic:  windows 10
- Target Devices: 
PC dev machine

**Comment by mattleibow** [comment] 2020-10-07 11:13
Ah, thanks for reporting this. This is really a result of avoiding a bigger problem.

Because the assembly for the net462 in SkiaSharp.Views.Forms is actually just a stub and throws. I found that people were using it and then exceptions were being thrown everywhere.
In the end, I decided that I should not let it ever get to that stage.

So, in order to make this code compile, you can pick from the _platform_ versions:
 - SkiaSharp.Views.Forms.WPF
 - SkiaSharp.Views.Forms.GTK

Let me know if this doesn't work, then I can see what I can do to make this experience better. I have been using it and it seems to be working just fine.

**Comment by mattleibow** [comment] 2020-10-22 00:30
Duplicate of https://github.com/mono/SkiaSharp/issues/1523

**Comment by mattleibow** [comment] 2020-10-22 00:31
Duplicate of https://github.com/mono/SkiaSharp/issues/1225

**Closed by mattleibow** 2020-10-22 00:30 UTC
