### ISSUE TITLE
SKSurface.Create returns null in 1.59.1

### ISSUE THREAD

**Issue by maxwell313** [mono/SkiaSharp#347] opened 2017-07-31 18:49 UTC
SKSurface.Create started to return null in 1.59.1, but worked fine in 1.57.1

```csharp
int w = 1968;
int h = 1412;
double dpi = 2.5;

WriteableBitmap bmp = new WriteableBitmap(w, h, dpi, dpi, PixelFormats.Pbgra32, null);
bmp.Lock();

using (var surface = SKSurface.Create(
              width: w,
              height: h,
              colorType: SKColorType.Bgra8888,
              alphaType: SKAlphaType.Premul,
              pixels: bmp.BackBuffer,
              rowBytes: w * 4))
            {
                SKCanvas canvas = surface.Canvas;   //surface is null at this point
            }

bmp.Unlock();
```

**Comment by maxwell313** [comment] 2017-07-31 19:23
Just tried it in a new project and it worked fine with 1.59.1, so likely not a Skia issue

**Comment by entdark** [comment] 2017-08-01 14:00
Happened to me as well:
`var newInfo = new SKImageInfo(
	width,
	height,
	SKColorType.Rgba8888,
	SKAlphaType.Premul);
using (var surface = SKSurface.Create(newInfo)) {
	this.DrawBlocks(surface.Canvas, newInfo); <- happens here, surface is null
}`

**Comment by mattleibow** [comment] 2017-08-01 14:47
Hi there guys - I need a bit more info. What platform is this? UWP? WPF?

**Comment by entdark** [comment] 2017-08-01 18:42
Tested on iOS and Android, did not get to UWP yet.
I have a guess that one of sizes was invalid like width or height is <= 0 or something?
I will be able to check the sizes tomorrow.

**Comment by entdark** [comment] 2017-08-02 06:42
My guess was correct: the width was negative.
It works now.

**Comment by entdark** [comment] 2017-08-03 06:00
Alright, it crashed again with surface being null on iOS and UWP (unable to test on Android right now) with positive values of width and height this time.
The newInfo from the sample above has the following:
```
- newInfo	{SkiaSharp.SKImageInfo}	SkiaSharp.SKImageInfo
	AlphaType	Premul	SkiaSharp.SKAlphaType
	BitsPerPixel	32	int
	BytesPerPixel	4	int
	BytesSize	338032	int
	BytesSize64	338032	long
+	ColorSpace	null	SkiaSharp.SKColorSpace
	ColorType	Rgba8888	SkiaSharp.SKColorType
	Height	148	int
	IsEmpty	false	bool
	IsOpaque	false	bool
+	Rect	{{Left=0,Top=0,Width=571,Height=148}}	SkiaSharp.SKRectI
	RowBytes	2284	int
	RowBytes64	2284	long
+	Size	{{Width=571, Height=148}}	SkiaSharp.SKSizeI
	Width	571	int

```

**Comment by mattleibow** [comment] 2017-09-12 21:01
@entdark The cause might be the incorrect color types per platform. Android and iOS should be fine with `Rgba8888`, but UWP must be `Bgra8888`. To avoid having to guess or try and determine the correct color, [`SKImageInfo.PlatformColorType`](https://developer.xamarin.com/api/field/SkiaSharp.SKImageInfo.PlatformColorType). The key word here is "typically", The actual color type depends on the underlying architecture and platform.

I am closing this as I think this solves the issue, but feel free to re-open if this is still `null`. **NOTE:** Make sure you have also installed the NuGets into the platform projects as well as any library projects.

**Closed by mattleibow** 2017-09-12 21:01 UTC
