### ISSUE TITLE
[ISSUE] The referenced component 'C:\Users\USERNAME\.nuget\packages\skiasharp\2.80.3\buildTransitive\xamarinios1.0\..\..\build\xamarinios1.0\libSkiaSharp.framework' could not be found.	

### ISSUE THREAD

**Issue by Auto72** [mono/SkiaSharp#1886] opened 2021-12-09 10:22 UTC
**Description**

I'm trying to compile my Xamarin Forms project  with Visual Studio 2022 and I'm getting the following error:

The referenced component 'C:\Users\USERNAME\.nuget\packages\skiasharp\2.80.3\buildTransitive\xamarinios1.0\..\..\build\xamarinios1.0\libSkiaSharp.framework' could not be found.	

**Code**

It seems a problem related to the NuGet package or reference, not a code problem.

**Expected Behavior**

No warning and able to compile and run the application.

**Actual Behavior**

Warning and the application does't run.

**Basic Information**

- Version with issue:  2.80.3
- Last known good version:  none
- IDE:  Visual Studio 2022
- Platform Target Frameworks: 
  - Android: 12
  - iOS:  Default SDK Version (15)

- Target Devices:   
- iPad Air 4th generation
  
<details>
I use Visual Studio 2022 now.
Before I had Visual Studio 2019 and I used to get this warning every time I compiled, but at that time I found an entry in the reference of the iOS project with yellow exclamation mark, and I was able to delete it and recompile.
Now, in Visual Studio 2022 I don't see this entry in the reference and I can't compile.
  
</details>

**Screenshots**
![2](https://user-images.githubusercontent.com/52780377/145377616-fabc1788-809f-4741-b3e2-dd8b595c9736.png)
![3](https://user-images.githubusercontent.com/52780377/145377625-51ef633b-3978-4c9c-8c44-96639e57232b.png)
![4](https://user-images.githubusercontent.com/52780377/145377634-1eccc2b2-c59d-4ff1-8fe7-6c66aa47fb81.png)

**Reproduction Link**

**Comment by ldl01031** [comment] 2022-03-05 06:26
I'm having this exact problem. Is there a solution?

**Comment by Auto72** [comment] 2022-03-07 08:06
I still having this issue and I am not aware of any fix or workaround.

Warning		
The referenced component 'C:\Users\USERNAME\.nuget\packages\skiasharp\2.80.3\buildTransitive\xamarinios1.0\..\..\build\xamarinios1.0\libSkiaSharp.framework' could not be found.

**Comment by Edgar-Develop** [comment] 2022-08-01 21:04
Hi, Anyone with the solution?

**Comment by djcsavoy** [comment] 2022-08-30 09:51
We had a very similar problem today - as it happened, removing all the skia package folders from C:\Users\<username>\.nuget\packages and doing a full rebuild in VS resolved it. Random guess: Somehow the native ios package had been corrupted, maybe when it was initially downloaded?

**Comment by mattleibow** [comment] 2024-04-24 07:50
Duplicate of https://github.com/mono/SkiaSharp/issues/2824

**Comment by mattleibow** [comment] 2024-04-24 07:57
The OP issue was probably a corrupted nuget download. Closing this for now, feel free to open a new issue if it returns.

**Closed by mattleibow** 2024-04-24 07:57 UTC
