### ISSUE TITLE
[QUESTION] 🚀 Emoji causes the pdf file to be too large

### ISSUE THREAD

**Issue by inbreaks** [mono/SkiaSharp#982] opened 2019-10-16 03:22 UTC
This question from [issues/232#issuecomment-528840847](https://github.com/mono/SkiaSharp/issues/232#issuecomment-528840847)
``` cs
// get the character code
// either:
var emojiChar = StringUtilities.GetUnicodeCharacterCode("🚀", SKTextEncoding.Utf32);
// or:
var emojiChar = 0x1F680;

// ask the font manager for a font with that character
var fontManager = SKFontManager.Default;
var emojiTypeface = fontManager.MatchCharacter(emojiChar);

// draw it
var paint = new SKPaint { Typeface = emoji };
canvas.DrawText("🌐 🍪 🍕 🚀", 20, 40, paint);
```

**Comment by mattleibow** [comment] 2019-10-21 19:28
Thanks for reporting this. Could you provide the SkiaSharp version as well as the OS platform?

**Comment by inbreaks** [comment] 2019-10-23 01:47
> Thanks for reporting this. Could you provide the SkiaSharp version as well as the OS platform?

@mattleibow 

* SkiaSharp 1.68.0
* mac OS Catelina && MoJava
* .NET Core 2.2 && 3.0

**Comment by mattleibow** [comment] 2020-06-10 23:42
Closing this as a duplicate of #848

**Closed by mattleibow** 2020-06-10 23:42 UTC
