### ISSUE TITLE
[BUG] System.TypeInitializationException : The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.

### ISSUE THREAD

**Issue by vijayasurya20** [mono/SkiaSharp#1050] opened 2019-12-03 13:47 UTC
**Description**

System.TypeInitializationException : The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
System.DllNotFoundException : Unable to load DLL 'libSkiaSharp': The specified module could not be found.

**Code**

We have created a .Net Framework test project referencing the .Net Standard library where the Library has "SkiaSharp" as one of its dependency package. While running the test project, we are facing the above mentioned exception.   

**Expected Behavior**

There should not be any exception

**Actual Behavior**

The type initializer for 'SkiaSharp.SKImageInfo' threw an exception occurs

**Basic Information**

- Version with issue:  <1.59.3>
- Last known good version:  <1.59.3>
- IDE:  
- Platform Target Frameworks: <!.Windows -->
 
- Target Devices:  
  - 
  - 

**Screenshots**

**Reproduction Link**

**Comment by vijayasurya20** [comment] 2019-12-03 13:49
Please find the test project  in which we are facing issue from the following link. 

[Test project.zip](https://github.com/mono/SkiaSharp/files/3916928/Test.project.zip)

**Comment by mattleibow** [comment] 2019-12-03 13:59
What happens if you install SkiaSharp into the test project?

I think the default project rules basically say not to include these native libraries. I am working on #1041 to see if this will fix this issue.

**Comment by vijayasurya20** [comment] 2019-12-03 14:11
Hi Mattlie,

Thank you for your update.

As you have mentioned, while installing the SkiaSharp into the test project works fine.

Since we have added the .Net Standard library project which has "SkiaSharp" as dependent package is added as dependency of Test project, then please let me know why should we need to add "SkiaSharp" package individually into the test project. Because the Library project itself should have every dependency it needs.

Regards,
Vijayasurya A

**Comment by mattleibow** [comment] 2019-12-03 17:33
I believe it is because the way the build works with the .net framework build. This actually won't happen with .net core. What is happening is that we have a .targets file that copies the native libraries from .net framework. But, with the new tooling, it ignores it unless you have a specific reference. 

This is the issue tracking that: https://github.com/mono/SkiaSharp/issues/1041

I'll release a fix as soon as I can, but the install into the test project is the way to do it now.

**Comment by mattleibow** [comment] 2019-12-03 18:59
Closing this as a duplicate of #1041

**Closed** 2019-12-22 04:50 UTC
Labels: type-bug, type-duplicate

**Comment by boonkerz** [comment] 2022-01-02 20:14
Hi i have the same issue:

System.TypeInitializationException
  HResult=0x80131534
  Nachricht = The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
  Quelle = Avalonia.Skia
  Stapelüberwachung:
   bei Avalonia.Skia.PlatformRenderInterface..ctor(ISkiaGpu skiaGpu, Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs: Zeile27
   bei Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs: Zeile21
   bei Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs: Zeile20
   bei Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs: Zeile305
   bei Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs: Zeile180
   bei Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs: Zeile175
   bei PscCloud.Program.Main(String[] args) in Z:\home\thomas\projekte\psccloud\PscCloud\Program.cs: Zeile13

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:
    [Externer Code]

Innere Ausnahme 1:
DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: Das angegebene Modul wurde nicht gefunden. (0x8007007E)
