### ISSUE TITLE
[BUG] Crashes on Android

### ISSUE THREAD

**Issue by hajmajeboss** [mono/SkiaSharp#1173] opened 2020-03-12 08:19 UTC
**Description**

I'm using mapping library Mapsui, error occurs randomly when moving the map, noticed some of the crashes even with map staying still. 

**Code**

```
I/DEBUG   (  409): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  409): UUID: 7bf113ad-494f-44e9-a0fe-61d0704bbee9
I/DEBUG   (  409): Build fingerprint: 'Sony/SGP321/SGP321:5.1.1/10.7.A.0.228/2020576680:user/release-keys'
I/DEBUG   (  409): Revision: '0'
I/DEBUG   (  409): ABI: 'arm'
I/DEBUG   (  409): pid: 19172, tid: 19229, name: GLThread 1370  >>> eu.pds.proplamobilenet <<<
I/DEBUG   (  409): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1110
I/DEBUG   (  409):     r0 00001110  r1 00000001  r2 9ec01088  r3 00000011
I/DEBUG   (  409):     r4 00000000  r5 12dcc740  r6 9ec01088  r7 9a8d3848
I/DEBUG   (  409):     r8 b74ebc10  r9 b849e9e0  sl 00000000  fp 9a8d3980
I/DEBUG   (  409):     ip afb8acbc  sp 9a8d3838  lr 9974f96c  pc 997d391e  cpsr 600d0030
I/DEBUG   (  409):
I/DEBUG   (  409): backtrace:
I/DEBUG   (  409):     #00 pc 0006191e  /data/app/eu.pds.proplamobilenet-1/lib/arm/libSkiaSharp.so
```

I also noticed an error **with address 0x40,** and p**ossibly 0x1130 (no .so file path in this case)** - can't find the stack trace now.

**Basic Information**

- Version with issue: 1.68.1.1.
- Last known good version: probably 1.60.3
- IDE:  Visual Studio
- Platform Target Frameworks: <
  - Android: API 27 (8.1)
- Target Devices:   
  - Xiaomi Mi A2
  - Sony Xperia Tablet Z

**Reproduction Link**

https://github.com/Mapsui/Mapsui - building a Mapsui.Samples.Droid project and running it on an Android device, trying especially geometries samples .

**Comment by mattleibow** [comment] 2020-03-12 10:42
This might be a duplicate of https://github.com/mono/SkiaSharp/issues/1121

Looking at the stack traces in the mapsui issue, this looks a bit similar.

**Comment by hajmajeboss** [comment] 2020-03-12 11:29
Yes, the description seems to fit. The very same crash is also happening on iOS, already told the poster of Mapsui/#865 to post the stack trace here.

**Comment by mattleibow** [comment] 2020-03-20 09:20
I have just published the PR (https://github.com/mono/SkiaSharp/pull/1180) NuGet (**1.68.2-pr.1180.1**) to the preview feed: https://aka.ms/skiasharp-eap/index.json
This contains the fixes for macOS, iOS and Android. More platforms coming soon.

Give that a go and let me know if it fixes the crashes.

**Closed** 2020-03-24 16:09 UTC

**Comment by mattleibow** [comment] 2020-03-24 21:04
Just pushed all the packages (preview 45) to NuGet.org.

**Comment by mattleibow** [comment] 2020-04-03 13:30
Hey folks, it has been a long time coming and thanks to all the folks with your repros, samples and stack traces I think we have finally managed to fix those pesky crashes - at least the ones we know about. I have just pushed **1.68.2-preview.50** to NuGet so let me know if this fixes all the crashes you have ever had 😄
