### ISSUE TITLE
[BUG] SkiaSharp.NativeAssets.macos is adding a reference to osx binary which cannot be found

### ISSUE THREAD

**Issue by alexachso** [mono/SkiaSharp#2223] opened 2022-08-24 19:48 UTC
**Description**

We get the following warning in visual studio for our WPF project:

Severity	Code	Description	Project	File	Line	Suppression State

Warning		The referenced component 'C:\Users\Alexandru Stefan Nea\.nuget\packages\harfbuzzsharp.nativeassets.macos\2.8.2.1-preview.91\buildTransitive\net462\..\..\runtimes\osx\native\libHarfBuzzSharp.dylib' could not be found.	ctServiceTool			
Warning		The referenced component 'C:\Users\Alexandru Stefan Nea\.nuget\packages\skiasharp.nativeassets.macos\2.88.1-preview.91\buildTransitive\net462\..\..\runtimes\osx\native\libSkiaSharp.dylib' could not be found.	ctServiceTool			

I am using a WPF project which only targets windows. I do not understand why it is throwing these macOS warnings. I manually traveled the path suggested and the file is there on the machine. I do not understand why Visual Studio says it cannot be found.

Could this be related to this? https://github.com/mono/SkiaSharp/issues/1159

**Basic Information**

- Version with issue:  2.88.1-preview.91 (I had the same issue with 2.88.0)
- IDE:  VS 2022
- Platform Target Frameworks: .net 4.7.2
- Target Devices:   Windows

**Comment by lasgor** [comment] 2024-03-31 11:50
I'm seeing this as well. In [this closed issue](https://github.com/mono/SkiaSharp/issues/2474) it supposedly is VS bug that was fixed at some point, but I'm running 17.9.5 and the issue is still there. The buildTransitive folder is not present, so that is why VS cannot find it. 

An excerpt from skiasharp.nuspec:
```
    <dependencies>
      <group targetFramework=".NETFramework4.6.2">
        <dependency id="SkiaSharp.NativeAssets.Win32" version="2.88.7" />
        <dependency id="SkiaSharp.NativeAssets.macOS" version="2.88.7" />
        <dependency id="System.Memory" version="4.5.5" />
      </group>
      <group targetFramework=".NETStandard1.3">
        <dependency id="SkiaSharp.NativeAssets.Win32" version="2.88.7" />
        <dependency id="SkiaSharp.NativeAssets.macOS" version="2.88.7" />
        <dependency id="System.IO.UnmanagedMemoryStream" version="4.3.0" />
        <dependency id="System.Memory" version="4.5.5" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="SkiaSharp.NativeAssets.Win32" version="2.88.7" />
        <dependency id="SkiaSharp.NativeAssets.macOS" version="2.88.7" />
        <dependency id="System.Memory" version="4.5.5" />
      </group>
      <group targetFramework=".NETStandard2.1">
        <dependency id="SkiaSharp.NativeAssets.Win32" version="2.88.7" />
        <dependency id="SkiaSharp.NativeAssets.macOS" version="2.88.7" />
      </group>
```
@mattleibow Could the issue be that macOS is included under .NETFramework4.6.2, but it should not (.NET Standard supports macOS, but .NET Framework does not)?

**Comment by rozeboosje** [comment] 2024-04-15 10:27
Thank you Luís,

As mentioned in my own issue, this needs to be addressed as it leaves me uncertain what to distribute with my .NET Framework 4.8 applications in order to ensure that it will work correctly.

**Comment by rozeboosje** [comment] 2024-04-19 14:27
Please note that I am running the most current Visual Studio build, Visual Studio Professional 2022, version 17.9.6

**Comment by rozeboosje** [comment] 2024-04-19 14:29
Related issue https://github.com/mono/SkiaSharp/issues/2474 has **not** been resolved.

**Comment by mattleibow** [comment] 2024-04-24 07:50
Duplicate of https://github.com/mono/SkiaSharp/issues/2824

**Closed by mattleibow** 2024-04-24 07:50 UTC
