### ISSUE TITLE
SkiaSharp.SkImageInfo threw an exception

### ISSUE THREAD

**Issue by Seanba** [mono/SkiaSharp#332] opened 2017-07-04 18:22 UTC
Hi there. Thanks for SkiaSharp. It's great. I've been using it in [Tiled2Unity](http://www.seanba.com/tiled2unity) for a couple months now.

However, I've got some Windows users reporting this exception to me:

> The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.

Sometimes this exception goes away for them (maybe after updating their .Net Framework, or OS) but I haven't been able to pin down much more information than that (sorry, I don't have access to their workstations and haven't been able to reproduce the error myself.)

I wonder if there's something going on with the static constructor on SKImageInfo? I see some platform specific code there.

```
static SKImageInfo ()
{
	PlatformColorType = SkiaApi.sk_colortype_get_default_8888 ();
	SkiaApi.sk_color_get_bit_shift (out PlatformColorAlphaShift, out PlatformColorRedShift, out PlatformColorGreenShift, out PlatformColorBlueShift);
}
```
BTW, this is appearing on Windows 10 64bit for some users. Other users are reporting it on Win8 64 as well.

**Comment by mattleibow** [comment] 2017-07-15 10:10
I am not too sure exactly, but the exception is probably related to the fact that it either can't find the native libSkiaSharp.dll, or is unable to load it (ie: it may be an x86 dll and you are on an x64 OS).

I will need to see more of the exception, but this is just SkiaSharp saying that it can't find or load the native bits.

**Comment by Seanba** [comment] 2017-08-28 04:06
It looks like SkiaSharp has a dependency on the Visual C++ Redistributable from Visual Studio 2015. I haven't confirmed it yet but I'm guessing some of my users don't have that installed.

**Comment by mattleibow** [comment] 2017-08-28 13:36
That is correct. There is a dependency on the redist. More info: #136

**Comment by mattleibow** [comment] 2017-09-01 19:02
Closing this as this is not a bug, but a requirement.

**Closed by mattleibow** 2017-09-01 19:02 UTC
