### ISSUE TITLE
SkiaBitmap.Encode always returns false for certain file types

### ISSUE THREAD

**Issue by Dameon13th** [mono/SkiaSharp#532] opened 2018-05-27 00:38 UTC
### Description

If I a either creating a new image or editing and existing file the SkBitmap.Encode method returns false.
The file that is created cannot be opened and is invalid or corrupt.

### Code

            SKImageInfo imageInfo = new SKImageInfo(1000, 800);
            using (SKBitmap bitmap = new SKBitmap(imageInfo))
            {
                SKCanvas canvas = new SKCanvas(bitmap);
                canvas.Clear(SKColors.White);

                using (SKWStream stream = new SKFileWStream("[File Path]"))
                {
                    bool results = bitmap.Encode(stream, SKEncodedImageFormat.Gif, 80);
                    // results are always false for GIF, ICO, WBMP
                }
            }

### Expected Behavior

The SkBitmap.Encode should return true and the file created\edited can be opened and viewed without issue.

### Actual Behavior

SkBitmap.Encode returns false and the file is corrupt\invalid.

### Basic Information

- Version with issue:  1.60.1
- Last known good version:  N\A
- IDE: VS2017
- Platform Target Frameworks: .NETstandard 2.0

- Target Devices: N\A (Library for use on several platforms)

**Comment by mattleibow** [comment] 2018-05-27 02:13
This is a known limitation: https://github.com/mono/SkiaSharp/issues/320#issuecomment-310805723

> ... by default, skia compiles with it's own codecs:
> https://github.com/mono/skia/blob/xamarin-mobile-bindings/src/images/SkImageEncoder.cpp
> Basically JPG, PNG, WEBP.
> … so I asked: https://groups.google.com/forum/#!topic/skia-discuss/a_HNOFtuyWg
> They said:
> > Android only needed JPG, PNG, and WEBP.  So that's what we provided them.
> > Until recently, we have had no other clients for our image encoders or decoders.
> > A client can always write their own with SkPixelSerializer.  
> > …
> > … these days even Windows supports PNGs.

**Comment by mattleibow** [comment] 2018-05-27 02:14
Duplicate of #320

**Closed by mattleibow** 2018-05-27 02:14 UTC

**Comment by Dameon13th** [comment] 2018-05-27 02:17
ok thanks for the quick response. I will try the SkPixelSerializer.
