### ISSUE TITLE
libSkiaSharp.dll missing when using dotnet publish

### ISSUE THREAD

**Issue by Ollhax** [mono/SkiaSharp#659] opened 2018-10-25 12:43 UTC
### Description

I'm using the following command to publish my program:
`dotnet publish -r win-x64`

When I run the resulting exe, I get this exception:
`System.DllNotFoundException: Unable to load DLL 'libSkiaSharp' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

Apparently it does not fetch the correct dll from the nuget package when using a [portable RID](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog). If I change to this:
`dotnet publish -r win10-x64`

It works just fine.

Think [this](https://github.com/mono/SkiaSharp/issues/430) is the same problem, but that issue is closed.

### Basic Information

- Version with issue:  1.60.3
- IDE: Visual Studio

**Comment by mattleibow** [comment] 2018-10-29 16:33
Thanks for reporting this. We have fixed this in https://github.com/mono/SkiaSharp/issues/599 and will be going out in a release very soon: v1.68.0.

Currently, the best RID to use is `win7-x64`

**Comment by mattleibow** [comment] 2018-10-29 16:33
duplicate of #599

**Closed** 2018-10-29 16:33 UTC
