### ISSUE TITLE
[QUESTION]  What do i have to do when deploying on WPF

### ISSUE THREAD

**Issue by JonasZieker** [mono/SkiaSharp#1796] opened 2021-09-03 16:22 UTC
The Problem

as soon as i install skiasharp via NuGet in a blank new WPF apllication i cant install it anymore after deployment. After clicking on setup and following a few steps a window appears saying:

"the validity of the application could not be checked. The process cannot continue"

On details is shows following error description:

"The strong name signature is not valid for the SkiaSharp.Views.Desktop.Common.dll assembly."

What i have tried so far

created several blank wpf apps and repeated the same procedure on 3 diffrent maschines with same result
followed the instruction Here and Here without success.
Thank you for every hint you can give me!

**Comment by mattleibow** [comment] 2021-09-06 21:48
I believe it is because of the changes in a previous commit. 

This should be fixed in 2.80.4-preview.2

Duplicate of https://github.com/mono/SkiaSharp/issues/1767

**Closed** 2021-09-06 21:52 UTC
