### ISSUE TITLE
[QUESTION] InvalidateSurface() invokes OnPaint event on dedicated android and iOS emulator but not on dedicated iOS

### ISSUE THREAD

**Issue by Christoph293** [mono/SkiaSharp#1170] opened 2020-03-10 16:33 UTC
As discussed in slack previously i have the following problem/question to SKCanvasView:

When i call `InvalidateSurface` in my custom control `CoordAxesControl` the 'OnPaintSurface' event is never invoked on a dedicated iOs device. On a dedicated android device and an ios emulator everything works fine.
Is anything missing? I've added the project repo link due to the fact that the project is minimal because it concentrates on the ui.

Setup:
Device: iPhone 8 (iOS 13.3.1)
Mac: MacBook Pro (macOS Catalina 10.15.3)
Xamarin Version:
Xamarin.IOS v4.0.30319
Xamarin.Forms v4.5.0.356

SkiaSharp:
SkiaSharp.Views.Forms (1.68.1.1)

Github repo: https://github.com/Christoph293/infoGraph/tree/master/InfoGraph/InfoGraph

**Comment by rebecca-networkapp** [comment] 2020-03-11 13:43
Hello,
I had the same problem after upgrading my iPad to 13.3.1, when using a [Free provisioning for Xamarin.iOS apps](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos) after changing to `Adhoc-Provisioning` it worked normally.

Hoop this helps.

**Comment by mattleibow** [comment] 2020-03-13 10:53
This is a duplicate of https://github.com/mono/SkiaSharp/issues/1129

**Closed by mattleibow** 2020-03-13 10:53 UTC
